import type { TopicQuestions } from "./types"

export const GRADE7_M1_QUESTIONS: TopicQuestions = {
  "m1-integers": [
    {
      id: "m1-grade7-int-1",
      curriculum: "M1",
      topicId: "m1-integers",
      topicName: "Integers",
      difficulty: "easy",
      question: "What is 7 + (-3)?",
      choices: ["4", "10", "-4", "-10"],
      answer: 0,
      explanation: "Adding a negative number means moving left on the number line. 7 + (-3) = 4.",
      solutionSteps: ["Start at 7 on the number line.", "Move 3 steps left because you are adding -3.", "You land on 4."],
      hints: ["Think of adding a negative as subtraction"],
      estimatedTime: 45,
      learningObjective: "Add and subtract integers using a number line.",
      tags: ["grade-7", "integers", "number-line"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-int-2",
      curriculum: "M1",
      topicId: "m1-integers",
      topicName: "Integers",
      difficulty: "medium",
      question: "What is (-8) ÷ 2?",
      choices: ["4", "-4", "16", "-16"],
      answer: 1,
      explanation: "A negative divided by a positive gives a negative result. (-8) ÷ 2 = -4.",
      solutionSteps: ["Divide 8 by 2 to get 4.", "The signs are different, so the answer is negative.", "The result is -4."],
      hints: ["Negative divided by positive is negative"],
      estimatedTime: 50,
      learningObjective: "Divide integers with different signs.",
      tags: ["grade-7", "integers", "division"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-fractions": [
    {
      id: "m1-grade7-frac-1",
      curriculum: "M1",
      topicId: "m1-fractions",
      topicName: "Fractions",
      difficulty: "easy",
      question: "What is 1/2 + 1/4?",
      choices: ["1/4", "2/4", "3/4", "1/8"],
      answer: 2,
      explanation: "Use a common denominator of 4. 1/2 = 2/4, so 2/4 + 1/4 = 3/4.",
      solutionSteps: ["Find a common denominator of 4.", "Rewrite 1/2 as 2/4.", "Add the numerators: 2 + 1 = 3, so the answer is 3/4."],
      hints: ["Convert to like denominators"],
      estimatedTime: 45,
      learningObjective: "Add fractions with unlike denominators.",
      tags: ["grade-7", "fractions", "addition"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-frac-2",
      curriculum: "M1",
      topicId: "m1-fractions",
      topicName: "Fractions",
      difficulty: "medium",
      question: "What is 3/4 of 20?",
      choices: ["5", "10", "15", "20"],
      answer: 2,
      explanation: "Find 3/4 of 20 by multiplying 20 by 3/4. 20 × 3/4 = 15.",
      solutionSteps: ["Divide 20 by 4 to get 5.", "Multiply 5 by 3 to get 15."],
      hints: ["Take 3 parts out of 4 equal parts"],
      estimatedTime: 50,
      learningObjective: "Find a fraction of a quantity.",
      tags: ["grade-7", "fractions", "of-a-number"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-decimals": [
    {
      id: "m1-grade7-dec-1",
      curriculum: "M1",
      topicId: "m1-decimals",
      topicName: "Decimals",
      difficulty: "easy",
      question: "What is 2.4 + 1.8?",
      choices: ["3.2", "4.2", "4.0", "3.0"],
      answer: 1,
      explanation: "Line up the decimal points and add. 2.4 + 1.8 = 4.2.",
      solutionSteps: ["Align the decimal points.", "Add the tenths: 4 + 8 = 12, write 2 and carry 1.", "Add the ones: 2 + 1 + 1 = 4."],
      hints: ["Keep the decimal points aligned"],
      estimatedTime: 45,
      learningObjective: "Add decimals accurately.",
      tags: ["grade-7", "decimals", "addition"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-dec-2",
      curriculum: "M1",
      topicId: "m1-decimals",
      topicName: "Decimals",
      difficulty: "medium",
      question: "What is 6.3 × 10?",
      choices: ["0.63", "63", "6.30", "0.063"],
      answer: 1,
      explanation: "Multiplying by 10 shifts the decimal point one place to the right. 6.3 × 10 = 63.",
      solutionSteps: ["Count the zero in 10.", "Move the decimal point one place right.", "6.3 becomes 63."],
      hints: ["Multiply by 10 moves the decimal right"],
      estimatedTime: 45,
      learningObjective: "Multiply decimals by powers of ten.",
      tags: ["grade-7", "decimals", "multiplication"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-linear-equations": [
    {
      id: "m1-grade7-eq-1",
      curriculum: "M1",
      topicId: "m1-linear-equations",
      topicName: "Linear Equations",
      difficulty: "easy",
      question: "Solve x + 5 = 12.",
      choices: ["x = 7", "x = 17", "x = 5", "x = 12"],
      answer: 0,
      explanation: "Subtract 5 from both sides to isolate x. x = 7.",
      solutionSteps: ["Start with x + 5 = 12.", "Subtract 5 from both sides.", "You get x = 7."],
      hints: ["Undo the +5 by subtracting 5"],
      estimatedTime: 45,
      learningObjective: "Solve one-step linear equations.",
      tags: ["grade-7", "linear-equations", "one-step"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-eq-2",
      curriculum: "M1",
      topicId: "m1-linear-equations",
      topicName: "Linear Equations",
      difficulty: "medium",
      question: "Solve 3x = 18.",
      choices: ["x = 6", "x = 15", "x = 21", "x = 54"],
      answer: 0,
      explanation: "Divide both sides by 3 to isolate x. 18 ÷ 3 = 6.",
      solutionSteps: ["Start with 3x = 18.", "Divide both sides by 3.", "x = 6."],
      hints: ["Undo multiplication by dividing"],
      estimatedTime: 45,
      learningObjective: "Solve one-step linear equations with multiplication.",
      tags: ["grade-7", "linear-equations", "division"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-ratio": [
    {
      id: "m1-grade7-ratio-1",
      curriculum: "M1",
      topicId: "m1-ratio",
      topicName: "Ratio",
      difficulty: "easy",
      question: "Write the ratio 6:8 in simplest form.",
      choices: ["2:3", "3:4", "4:3", "1:2"],
      answer: 1,
      explanation: "Divide both terms by 2. 6:8 simplifies to 3:4.",
      solutionSteps: ["Find the greatest common factor of 6 and 8.", "Divide both numbers by 2.", "The simplest form is 3:4."],
      hints: ["Divide both parts by the same number"],
      estimatedTime: 45,
      learningObjective: "Simplify ratios.",
      tags: ["grade-7", "ratio", "simplify"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-ratio-2",
      curriculum: "M1",
      topicId: "m1-ratio",
      topicName: "Ratio",
      difficulty: "medium",
      question: "If the ratio of boys to girls is 2:3 and there are 10 boys, how many girls are there?",
      choices: ["12", "15", "18", "20"],
      answer: 1,
      explanation: "The ratio 2:3 means for every 2 boys there are 3 girls. If there are 10 boys, multiply both terms by 5, giving 15 girls.",
      solutionSteps: ["Use the scale factor 10 ÷ 2 = 5.", "Multiply 3 by 5 to get 15.", "There are 15 girls."],
      hints: ["Use the same multiplier for both parts"],
      estimatedTime: 60,
      learningObjective: "Use ratio to find an unknown quantity.",
      tags: ["grade-7", "ratio", "word-problem"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-percentage": [
    {
      id: "m1-grade7-perc-1",
      curriculum: "M1",
      topicId: "m1-percentage",
      topicName: "Percentage",
      difficulty: "easy",
      question: "What is 25% of 80?",
      choices: ["10", "20", "30", "40"],
      answer: 1,
      explanation: "25% means one quarter. One quarter of 80 is 20.",
      solutionSteps: ["Convert 25% to 1/4.", "Divide 80 by 4.", "The result is 20."],
      hints: ["25% is one quarter"],
      estimatedTime: 45,
      learningObjective: "Find a percentage of a quantity.",
      tags: ["grade-7", "percentage", "of-a-number"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-perc-2",
      curriculum: "M1",
      topicId: "m1-percentage",
      topicName: "Percentage",
      difficulty: "medium",
      question: "What is 12 as a percentage of 48?",
      choices: ["20%", "25%", "30%", "35%"],
      answer: 1,
      explanation: "12 out of 48 is 1/4 of the total, which is 25%.",
      solutionSteps: ["Write 12/48 and simplify to 1/4.", "Convert 1/4 to a percentage by multiplying by 100.", "The answer is 25%."],
      hints: ["Use part over whole and multiply by 100"],
      estimatedTime: 60,
      learningObjective: "Express one number as a percentage of another.",
      tags: ["grade-7", "percentage", "comparison"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-geometry": [
    {
      id: "m1-grade7-geo-1",
      curriculum: "M1",
      topicId: "m1-geometry",
      topicName: "Geometry",
      difficulty: "easy",
      question: "What is the sum of the interior angles of a triangle?",
      choices: ["90°", "180°", "270°", "360°"],
      answer: 1,
      explanation: "The interior angles of a triangle always add to 180°.",
      solutionSteps: ["Recall the triangle angle rule.", "The total is 180°.", "So the sum is 180°."],
      hints: ["Triangle angles add to 180"],
      estimatedTime: 40,
      learningObjective: "Understand triangle angle facts.",
      tags: ["grade-7", "geometry", "angles"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-geo-2",
      curriculum: "M1",
      topicId: "m1-geometry",
      topicName: "Geometry",
      difficulty: "medium",
      question: "What type of angle is 90°?",
      choices: ["Acute", "Right", "Obtuse", "Straight"],
      answer: 1,
      explanation: "An angle of 90° is called a right angle.",
      solutionSteps: ["Compare the angle measure to 90°.", "If it equals 90°, it is a right angle."],
      hints: ["A square corner is 90°"],
      estimatedTime: 40,
      learningObjective: "Classify angles by size.",
      tags: ["grade-7", "geometry", "angles"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-area": [
    {
      id: "m1-grade7-area-1",
      curriculum: "M1",
      topicId: "m1-area",
      topicName: "Area",
      difficulty: "easy",
      question: "What is the area of a rectangle with length 8 and width 3?",
      choices: ["11", "24", "22", "18"],
      answer: 1,
      explanation: "Area of a rectangle is length × width. 8 × 3 = 24.",
      solutionSteps: ["Use the formula area = length × width.", "Substitute 8 and 3.", "Multiply to get 24."],
      hints: ["Multiply length by width"],
      estimatedTime: 45,
      learningObjective: "Calculate rectangle area.",
      tags: ["grade-7", "area", "rectangle"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-area-2",
      curriculum: "M1",
      topicId: "m1-area",
      topicName: "Area",
      difficulty: "medium",
      question: "What is the area of a triangle with base 10 and height 4?",
      choices: ["20", "40", "14", "28"],
      answer: 0,
      explanation: "Area of a triangle is 1/2 × base × height. 1/2 × 10 × 4 = 20.",
      solutionSteps: ["Use the triangle formula.", "Multiply 10 by 4 to get 40.", "Halve 40 to get 20."],
      hints: ["Triangle area is half of a rectangle"],
      estimatedTime: 60,
      learningObjective: "Calculate triangle area.",
      tags: ["grade-7", "area", "triangle"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-volume": [
    {
      id: "m1-grade7-vol-1",
      curriculum: "M1",
      topicId: "m1-volume",
      topicName: "Volume",
      difficulty: "easy",
      question: "What is the volume of a cuboid with length 4, width 3, and height 2?",
      choices: ["12", "20", "24", "18"],
      answer: 2,
      explanation: "Volume is length × width × height. 4 × 3 × 2 = 24.",
      solutionSteps: ["Use the formula volume = length × width × height.", "Multiply 4 × 3 = 12.", "Multiply 12 × 2 = 24."],
      hints: ["Volume uses three dimensions"],
      estimatedTime: 45,
      learningObjective: "Calculate cuboid volume.",
      tags: ["grade-7", "volume", "cuboid"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-vol-2",
      curriculum: "M1",
      topicId: "m1-volume",
      topicName: "Volume",
      difficulty: "medium",
      question: "What is the volume of a cube with side length 5?",
      choices: ["25", "75", "125", "150"],
      answer: 2,
      explanation: "Volume of a cube is side × side × side. 5 × 5 × 5 = 125.",
      solutionSteps: ["Use the cube formula.", "Multiply 5 by 5 to get 25.", "Multiply 25 by 5 to get 125."],
      hints: ["Cube means three equal factors"],
      estimatedTime: 60,
      learningObjective: "Calculate cube volume.",
      tags: ["grade-7", "volume", "cube"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-graphs": [
    {
      id: "m1-grade7-graph-1",
      curriculum: "M1",
      topicId: "m1-graphs",
      topicName: "Graphs",
      difficulty: "easy",
      question: "Which axis is horizontal?",
      choices: ["x-axis", "y-axis", "z-axis", "diagonal axis"],
      answer: 0,
      explanation: "The horizontal axis is the x-axis.",
      solutionSteps: ["Recall the orientation of the coordinate plane.", "The horizontal line is the x-axis."],
      hints: ["Think left-right"],
      estimatedTime: 35,
      learningObjective: "Identify graph axes.",
      tags: ["grade-7", "graphs", "axes"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-graph-2",
      curriculum: "M1",
      topicId: "m1-graphs",
      topicName: "Graphs",
      difficulty: "medium",
      question: "If a point is at (3, 2), how many units right is it from the origin?",
      choices: ["2", "3", "5", "0"],
      answer: 1,
      explanation: "The x-coordinate tells how far right the point is. (3, 2) is 3 units right.",
      solutionSteps: ["Read the x-coordinate.", "The x-coordinate is 3.", "The point is 3 units to the right."],
      hints: ["Look at the first number in the pair"],
      estimatedTime: 45,
      learningObjective: "Read coordinates on a graph.",
      tags: ["grade-7", "graphs", "coordinates"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-statistics": [
    {
      id: "m1-grade7-stat-1",
      curriculum: "M1",
      topicId: "m1-statistics",
      topicName: "Statistics",
      difficulty: "easy",
      question: "What is the mean of 2, 4, and 6?",
      choices: ["2", "4", "6", "8"],
      answer: 1,
      explanation: "The mean is the sum divided by the number of values. (2 + 4 + 6) ÷ 3 = 4.",
      solutionSteps: ["Add the values: 2 + 4 + 6 = 12.", "Divide by 3 because there are 3 values.", "The mean is 4."],
      hints: ["Average means sum divided by count"],
      estimatedTime: 45,
      learningObjective: "Find the mean of a set of data.",
      tags: ["grade-7", "statistics", "mean"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-stat-2",
      curriculum: "M1",
      topicId: "m1-statistics",
      topicName: "Statistics",
      difficulty: "medium",
      question: "What is the mode of 1, 2, 2, 3, 4?",
      choices: ["1", "2", "3", "4"],
      answer: 1,
      explanation: "The mode is the value that appears most often. 2 appears twice, more than any other value.",
      solutionSteps: ["Count each number's frequency.", "2 appears most often.", "The mode is 2."],
      hints: ["Look for the most frequent value"],
      estimatedTime: 40,
      learningObjective: "Find the mode of a data set.",
      tags: ["grade-7", "statistics", "mode"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
  "m1-basic-probability": [
    {
      id: "m1-grade7-prob-1",
      curriculum: "M1",
      topicId: "m1-basic-probability",
      topicName: "Basic Probability",
      difficulty: "easy",
      question: "A fair coin is flipped once. What is the probability of heads?",
      choices: ["0", "1/2", "1", "2"],
      answer: 1,
      explanation: "A fair coin has two equally likely outcomes: heads or tails. So the probability of heads is 1/2.",
      solutionSteps: ["Identify the possible outcomes.", "There are 2 equally likely outcomes.", "One outcome is heads, so the probability is 1/2."],
      hints: ["Probability = favorable outcomes over total outcomes"],
      estimatedTime: 40,
      learningObjective: "Find the probability of a simple event.",
      tags: ["grade-7", "probability", "fair-coin"],
      source: "Math Mentor AI",
      version: 1,
    },
    {
      id: "m1-grade7-prob-2",
      curriculum: "M1",
      topicId: "m1-basic-probability",
      topicName: "Basic Probability",
      difficulty: "medium",
      question: "A bag contains 3 red balls and 2 blue balls. What is the probability of drawing a red ball?",
      choices: ["1/5", "2/5", "3/5", "4/5"],
      answer: 2,
      explanation: "There are 5 total balls and 3 red balls. Probability = 3/5.",
      solutionSteps: ["Count the total number of balls: 3 + 2 = 5.", "Count the favorable outcomes: 3 red balls.", "Write the probability as 3/5."],
      hints: ["Use favorable over total"],
      estimatedTime: 60,
      learningObjective: "Find the probability from a simple sample space.",
      tags: ["grade-7", "probability", "sample-space"],
      source: "Math Mentor AI",
      version: 1,
    },
  ],
}
