import type { TopicQuestions } from "./types"

export const M1_QUESTIONS = {
  "m1-integers": [
    {
      id: "m1-int-e1", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "easy",
      question: "5 + (-3) เท่ากับอะไร?",
      choices: ["2", "8", "-2", "-8"],
      answer: 0,
      explanation: "บวกจำนวนเต็มลบ คือ ลบจำนวน absolute value: 5 - 3 = 2",
      hints: ["นึกถึงเส้นจำนวน: 5 ก้าวไปทางซ้าย 3 ก้าว"],
    },
    {
      id: "m1-int-e2", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "easy",
      question: "-4 × (-2) เท่ากับอะไร?",
      choices: ["-8", "8", "-6", "6"],
      answer: 1,
      explanation: "จำนวนลบคูณจำนวนลบได้จำนวนบวก: -4 × -2 = 8",
      hints: ["ลบ × ลบ = บวก", "4 × 2 = 8"],
    },
    {
      id: "m1-int-e3", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "easy",
      question: "10 - 15 เท่ากับอะไร?",
      choices: ["5", "-5", "25", "-25"],
      answer: 1,
      explanation: "10 ลบ 15 ได้ -5",
      hints: ["10 - 15 = -(15 - 10)"],
    },
    {
      id: "m1-int-e4", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "easy",
      question: "-6 ÷ 2 เท่ากับอะไร?",
      choices: ["-3", "3", "-12", "12"],
      answer: 0,
      explanation: "จำนวนลบหารจำนวนบวกได้จำนวนลบ: -6 ÷ 2 = -3",
      hints: ["ลบ ÷ บวก = ลบ"],
    },
    {
      id: "m1-int-e5", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "easy",
      question: "(-7) + (+4) เท่ากับอะไร?",
      choices: ["-11", "-3", "3", "11"],
      answer: 1,
      explanation: "จำนวนลบบวกจำนวนบวก: 7 - 4 = 3 แต่เครื่องหมายติดลบ ดังนั้น -3",
      hints: ["7 - 4 = 3, เครื่องหมายตามจำนวนที่มากกว่า"],
    },
    {
      id: "m1-int-m1", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "medium",
      question: "(-8) + (-3) - (-5) เท่ากับอะไร?",
      choices: ["-6", "-16", "6", "0"],
      answer: 0,
      explanation: "(-8) + (-3) = -11, -11 - (-5) = -11 + 5 = -6",
      hints: ["ลบด้วยจำนวนลบ = บวก", "(-8) + (-3) = -11", "-11 + 5 = -6"],
    },
    {
      id: "m1-int-m2", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "medium",
      question: "(-12) ÷ (-3) × (-2) เท่ากับอะไร?",
      choices: ["-8", "8", "-18", "18"],
      answer: 0,
      explanation: "(-12) ÷ (-3) = 4, 4 × (-2) = -8",
      hints: ["หารก่อน: (-12) ÷ (-3) = 4", "แล้วคูณ: 4 × (-2) = -8"],
    },
    {
      id: "m1-int-m3", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "medium",
      question: "ค่าสัมบูรณ์ของ | -15 | คืออะไร?",
      choices: ["-15", "15", "0", "-1"],
      answer: 1,
      explanation: "ค่าสัมบูรณ์คือระยะห่างจาก 0 บนเส้นจำนวน ดังนั้น | -15 | = 15",
      hints: ["ค่าสัมบูรณ์มีค่าเป็นบวกเสมอ"],
    },
    {
      id: "m1-int-m4", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "medium",
      question: "| -7 | - | 3 | เท่ากับอะไร?",
      choices: ["-4", "4", "-10", "10"],
      answer: 1,
      explanation: "| -7 | = 7, | 3 | = 3, 7 - 3 = 4",
      hints: ["หาค่าสัมบูรณ์ก่อน", "7 - 3 = 4"],
    },
    {
      id: "m1-int-m5", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "medium",
      question: "(-2)³ เท่ากับอะไร?",
      choices: ["-8", "8", "-6", "6"],
      answer: 0,
      explanation: "(-2)³ = (-2) × (-2) × (-2) = 4 × (-2) = -8",
      hints: ["(-2) × (-2) = 4", "จากนั้น 4 × (-2) = -8"],
    },
    {
      id: "m1-int-h1", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "hard",
      question: "ถ้า a = -5, b = -3 แล้ว a² - 2ab + b² เท่ากับอะไร?",
      choices: ["4", "16", "-4", "-16"],
      answer: 0,
      explanation: "a² = 25, 2ab = 2(-5)(-3) = 30, b² = 9, 25 - 30 + 9 = 4",
      hints: ["แทนค่า a = -5, b = -3", "a² = 25, b² = 9", "2ab = 2(15) = 30"],
    },
    {
      id: "m1-int-h2", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "hard",
      question: "(-2)⁴ - (-3)² + (-1)⁵ เท่ากับอะไร?",
      choices: ["6", "8", "24", "-6"],
      answer: 0,
      explanation: "(-2)⁴ = 16, (-3)² = 9, (-1)⁵ = -1, 16 - 9 + (-1) = 6",
      hints: ["(-2)⁴ = 16 (เลขคู่ = บวก)", "(-3)² = 9", "(-1)⁵ = -1 (เลขคี่ = ลบ)"],
    },
    {
      id: "m1-int-h3", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "hard",
      question: "จำนวนเต็มระหว่าง -5 ถึง 3 มีกี่จำนวน?",
      choices: ["7", "8", "9", "6"],
      answer: 0,
      explanation: "-5, -4, -3, -2, -1, 0, 1, 2, 3 รวม 9 จำนวน เฉพาะระหว่างไม่รวม -5 และ 3 คือ 7 จำนวน",
      hints: ["นับจำนวนเต็มระหว่าง -5 กับ 3", "ไม่รวม -5 และ 3"],
    },
    {
      id: "m1-int-h4", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "hard",
      question: "ผลบวกของ (-15) + (-20) + 25 + (-10) เท่ากับอะไร?",
      choices: ["-20", "20", "0", "-10"],
      answer: 0,
      explanation: "(-15) + (-20) = -35, -35 + 25 = -10, -10 + (-10) = -20",
      hints: ["รวมจำนวนลบก่อน", "(-35) + 25 = -10", "-10 + (-10) = -20"],
    },
    {
      id: "m1-int-h5", curriculum: "M1", topicId: "m1-integers", topicName: "จำนวนเต็ม", difficulty: "hard",
      question: "ถ้า x < 0 และ y < 0 แล้วข้อใดถูกต้อง?",
      choices: ["x + y > 0", "x × y > 0", "x - y < 0", "x ÷ y < 0"],
      answer: 1,
      explanation: "จำนวนลบคูณจำนวนลบได้จำนวนบวก ดังนั้น x × y > 0",
      hints: ["ลบ × ลบ = บวก", "ทดลองแทน x = -2, y = -3"],
    },
  ],
  "m1-exponents": [
    {
      id: "m1-exp-e1", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "easy",
      question: "2^3 เท่ากับอะไร?",
      choices: ["6", "8", "9", "4"],
      answer: 1,
      explanation: "2^3 = 2 × 2 × 2 = 8",
      hints: ["2 × 2 = 4", "4 × 2 = 8"],
    },
    {
      id: "m1-exp-e2", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "easy",
      question: "5^0 เท่ากับอะไร?",
      choices: ["0", "1", "5", "25"],
      answer: 1,
      explanation: "เลขยกกำลัง 0 ของจำนวนใดๆ (ยกเว้น 0) เท่ากับ 1",
      hints: ["a^0 = 1 เสมอเมื่อ a ≠ 0"],
    },
    {
      id: "m1-exp-e3", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "easy",
      question: "3^2 × 3^3 เท่ากับอะไร?",
      choices: ["3^5", "3^6", "9^5", "9^6"],
      answer: 0,
      explanation: "เมื่อคูณเลขยกกำลังที่มีฐานเดียวกัน ให้บวกเลขชี้กำลัง: 3^(2+3) = 3^5",
      hints: ["ฐานเหมือนกันให้บวกเลขชี้กำลัง", "2 + 3 = 5"],
    },
    {
      id: "m1-exp-e4", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "easy",
      question: "10^4 เท่ากับอะไร?",
      choices: ["1000", "10000", "100000", "40"],
      answer: 1,
      explanation: "10^4 = 10 × 10 × 10 × 10 = 10000",
      hints: ["10^1 = 10, 10^2 = 100, 10^3 = 1000"],
    },
    {
      id: "m1-exp-e5", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "easy",
      question: "4^2 เท่ากับอะไร?",
      choices: ["8", "12", "16", "20"],
      answer: 2,
      explanation: "4^2 = 4 × 4 = 16",
      hints: ["4 × 4 = 16"],
    },
    {
      id: "m1-exp-m1", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "medium",
      question: "(2^3)^2 เท่ากับอะไร?",
      choices: ["2^5", "2^6", "4^3", "4^5"],
      answer: 1,
      explanation: "เมื่อยกกำลังสอง ให้คูณเลขชี้กำลัง: 2^(3×2) = 2^6",
      hints: ["(a^m)^n = a^(m×n)", "3 × 2 = 6"],
    },
    {
      id: "m1-exp-m2", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "medium",
      question: "2^5 ÷ 2^2 เท่ากับอะไร?",
      choices: ["2^3", "2^7", "1^3", "2^10"],
      answer: 0,
      explanation: "เมื่อหารเลขยกกำลังฐานเดียวกัน ให้ลบเลขชี้กำลัง: 2^(5-2) = 2^3 = 8",
      hints: ["a^m ÷ a^n = a^(m-n)", "5 - 2 = 3"],
    },
    {
      id: "m1-exp-m3", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "medium",
      question: "(-2)^3 เท่ากับอะไร?",
      choices: ["-8", "8", "-6", "6"],
      answer: 0,
      explanation: "(-2)^3 = (-2) × (-2) × (-2) = 4 × (-2) = -8",
      hints: ["เลขชี้กำลังคี่ เครื่องหมายยังเป็นลบ"],
    },
    {
      id: "m1-exp-m4", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "medium",
      question: "3^4 - 3^2 เท่ากับอะไร?",
      choices: ["72", "81", "9", "64"],
      answer: 0,
      explanation: "3^4 = 81, 3^2 = 9, 81 - 9 = 72",
      hints: ["3^4 = 3 × 3 × 3 × 3 = 81", "3^2 = 9"],
    },
    {
      id: "m1-exp-m5", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "medium",
      question: "7^2 + 7^2 เท่ากับอะไร?",
      choices: ["7^4", "2×7^2", "14^2", "49^2"],
      answer: 1,
      explanation: "7^2 + 7^2 = 49 + 49 = 98 = 2 × 7^2",
      hints: ["7^2 = 49", "49 + 49 = 2 × 49"],
    },
    {
      id: "m1-exp-h1", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "hard",
      question: "(2^3 × 2^4) ÷ 2^5 เท่ากับอะไร?",
      choices: ["2^2", "2^3", "2^7", "2^12"],
      answer: 0,
      explanation: "2^3 × 2^4 = 2^7, 2^7 ÷ 2^5 = 2^2 = 4",
      hints: ["บวกเลขชี้กำลังก่อน: 3+4=7", "แล้วลบ: 7-5=2"],
    },
    {
      id: "m1-exp-h2", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "hard",
      question: "(-1)^100 + (-1)^101 เท่ากับอะไร?",
      choices: ["0", "2", "-2", "1"],
      answer: 0,
      explanation: "(-1)^100 = 1 (เลขคู่), (-1)^101 = -1 (เลขคี่), 1 + (-1) = 0",
      hints: ["เลขคู่ได้ 1, เลขคี่ได้ -1"],
    },
    {
      id: "m1-exp-h3", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "hard",
      question: "2^6 - 2^5 เท่ากับอะไร?",
      choices: ["32", "64", "16", "48"],
      answer: 0,
      explanation: "2^6 = 64, 2^5 = 32, 64 - 32 = 32",
      hints: ["2^6 = 64", "2^5 = 32"],
    },
    {
      id: "m1-exp-h4", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "hard",
      question: "ถ้า 2^x = 32 แล้ว x มีค่าเท่าไร?",
      choices: ["4", "5", "6", "3"],
      answer: 1,
      explanation: "2^5 = 32 ดังนั้น x = 5",
      hints: ["2^1=2, 2^2=4, 2^3=8, 2^4=16, 2^5=32"],
    },
    {
      id: "m1-exp-h5", curriculum: "M1", topicId: "m1-exponents", topicName: "เลขยกกำลัง", difficulty: "hard",
      question: "(2^2)^3 × 2^1 เท่ากับอะไร?",
      choices: ["2^7", "2^6", "2^8", "2^5"],
      answer: 0,
      explanation: "(2^2)^3 = 2^6, 2^6 × 2^1 = 2^7",
      hints: ["(2^2)^3 = 2^(2×3) = 2^6", "2^6 × 2^1 = 2^(6+1) = 2^7"],
    },
  ],
  "m1-linear-equations": [
    {
      id: "m1-le-e1", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "easy",
      question: "หาค่า x: 2x + 5 = 15",
      choices: ["x = 5", "x = 10", "x = 7.5", "x = 4"],
      answer: 0,
      explanation: "ลบ 5 จากทั้งสองด้าน: 2x = 10, หารด้วย 2: x = 5",
      hints: ["ย้าย 5 ไปอีกด้าน", "2x = 10", "x = 5"],
    },
    {
      id: "m1-le-e2", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "easy",
      question: "หาค่า x: 3x - 7 = 2",
      choices: ["x = 3", "x = 5", "x = -3", "x = 1"],
      answer: 0,
      explanation: "บวก 7: 3x = 9, หารด้วย 3: x = 3",
      hints: ["3x - 7 = 2", "3x = 9", "x = 3"],
    },
    {
      id: "m1-le-e3", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "easy",
      question: "หาค่า x: x/4 + 3 = 7",
      choices: ["x = 12", "x = 16", "x = 20", "x = 8"],
      answer: 1,
      explanation: "ลบ 3: x/4 = 4, คูณ 4: x = 16",
      hints: ["x/4 + 3 = 7", "x/4 = 4", "x = 16"],
    },
    {
      id: "m1-le-e4", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "easy",
      question: "หาค่า x: 5x = 35",
      choices: ["x = 5", "x = 7", "x = 30", "x = 175"],
      answer: 1,
      explanation: "หารทั้งสองด้านด้วย 5: x = 7",
      hints: ["5x = 35", "x = 35/5"],
    },
    {
      id: "m1-le-e5", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "easy",
      question: "หาค่า x: x - 8 = 12",
      choices: ["x = 4", "x = 20", "x = -4", "x = 96"],
      answer: 1,
      explanation: "บวก 8 ทั้งสองด้าน: x = 20",
      hints: ["x - 8 = 12", "x = 12 + 8"],
    },
    {
      id: "m1-le-m1", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "medium",
      question: "หาค่า x: 2(x - 3) = 8",
      choices: ["x = 5", "x = 7", "x = 11", "x = -1"],
      answer: 1,
      explanation: "กระจาย: 2x - 6 = 8, บวก 6: 2x = 14, หาร 2: x = 7",
      hints: ["กระจาย 2 เข้าไปในวงเล็บก่อน", "2x - 6 = 8", "2x = 14"],
    },
    {
      id: "m1-le-m2", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "medium",
      question: "หาค่า x: 4x + 5 = 2x + 13",
      choices: ["x = 3", "x = 4", "x = 8", "x = 2"],
      answer: 1,
      explanation: "ย้าย 2x: 2x + 5 = 13, ลบ 5: 2x = 8, หาร 2: x = 4",
      hints: ["ย้ายพจน์ x ไปด้านเดียวกัน", "4x - 2x + 5 = 13", "2x = 8"],
    },
    {
      id: "m1-le-m3", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "medium",
      question: "หาค่า x: 3(x + 2) = 2(x + 5)",
      choices: ["x = 4", "x = 6", "x = 3", "x = 1"],
      answer: 0,
      explanation: "3x + 6 = 2x + 10, 3x - 2x = 10 - 6, x = 4",
      hints: ["กระจายทั้งสองข้าง", "3x + 6 = 2x + 10", "x = 4"],
    },
    {
      id: "m1-le-m4", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "medium",
      question: "หาค่า x: (x/2) + 1 = 5",
      choices: ["x = 6", "x = 8", "x = 12", "x = 4"],
      answer: 1,
      explanation: "ลบ 1: x/2 = 4, คูณ 2: x = 8",
      hints: ["x/2 + 1 = 5", "x/2 = 4", "x = 8"],
    },
    {
      id: "m1-le-m5", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "medium",
      question: "ผลบวกของจำนวนสองจำนวนคือ 20 ถ้าจำนวนหนึ่งคือ x อีกจำนวนคือ?",
      choices: ["20 - x", "x - 20", "20 + x", "20x"],
      answer: 0,
      explanation: "x + (อีกจำนวน) = 20 ดังนั้นอีกจำนวน = 20 - x",
      hints: ["x + y = 20", "y = 20 - x"],
    },
    {
      id: "m1-le-h1", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "hard",
      question: "หาค่า x: 5(x - 3) = 3(x + 1)",
      choices: ["x = 9", "x = 6", "x = 12", "x = 3"],
      answer: 0,
      explanation: "5x - 15 = 3x + 3, 5x - 3x = 3 + 15, 2x = 18, x = 9",
      hints: ["5x - 15 = 3x + 3", "2x = 18", "x = 9"],
    },
    {
      id: "m1-le-h2", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "hard",
      question: "หาค่า x: (2x - 1)/3 = 5",
      choices: ["x = 8", "x = 7", "x = 6", "x = 9"],
      answer: 0,
      explanation: "คูณ 3: 2x - 1 = 15, บวก 1: 2x = 16, หาร 2: x = 8",
      hints: ["(2x-1)/3 = 5", "2x - 1 = 15", "2x = 16"],
    },
    {
      id: "m1-le-h3", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "hard",
      question: "สามเท่าของจำนวนหนึ่งลบด้วย 7 เท่ากับ 20 จำนวนนั้นคือ?",
      choices: ["9", "13", "27/3", "7"],
      answer: 0,
      explanation: "3x - 7 = 20, 3x = 27, x = 9",
      hints: ["ให้จำนวนนั้นคือ x", "3x - 7 = 20", "3x = 27"],
    },
    {
      id: "m1-le-h4", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "hard",
      question: "หาค่า x: 0.5x + 1.5 = 4.5",
      choices: ["x = 6", "x = 8", "x = 3", "x = 12"],
      answer: 0,
      explanation: "ลบ 1.5: 0.5x = 3, คูณ 2: x = 6",
      hints: ["0.5x + 1.5 = 4.5", "0.5x = 3", "x = 6"],
    },
    {
      id: "m1-le-h5", curriculum: "M1", topicId: "m1-linear-equations", topicName: "สมการเชิงเส้น", difficulty: "hard",
      question: "ผลต่างของจำนวนสองจำนวนคือ 8 ถ้าจำนวนมากคือ x จำนวนน้อยคือ?",
      choices: ["x - 8", "8 - x", "x + 8", "8x"],
      answer: 0,
      explanation: "x - (จำนวนน้อย) = 8 ดังนั้นจำนวนน้อย = x - 8",
      hints: ["x - y = 8", "y = x - 8"],
    },
  ],
  "m1-basic-geometry": [
    {
      id: "m1-geo-e1", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "easy",
      question: "ผลรวมมุมภายในของสามเหลี่ยมคือ?",
      choices: ["90°", "180°", "270°", "360°"],
      answer: 1,
      explanation: "มุมภายในสามเหลี่ยมทุกสามมุมมีผลรวม 180°",
      hints: ["จำไว้ว่าสามเหลี่ยม = 180 องศา"],
    },
    {
      id: "m1-geo-e2", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "easy",
      question: "พื้นที่สี่เหลี่ยมผืนผ้า กว้าง 6 ยาว 9 คือ?",
      choices: ["15", "27", "54", "36"],
      answer: 2,
      explanation: "พื้นที่ = กว้าง × ยาว = 6 × 9 = 54",
      hints: ["พื้นที่ = กว้าง × ยาว"],
    },
    {
      id: "m1-geo-e3", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "easy",
      question: "เส้นรอบวงของวงกลมรัศมี 7 คือ?",
      choices: ["7π", "14π", "21π", "49π"],
      answer: 1,
      explanation: "เส้นรอบวง = 2πr = 2π × 7 = 14π",
      hints: ["เส้นรอบวง = 2πr"],
    },
    {
      id: "m1-geo-e4", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "easy",
      question: "พื้นที่สามเหลี่ยมฐาน 8 สูง 5 คือ?",
      choices: ["13", "20", "40", "80"],
      answer: 1,
      explanation: "พื้นที่ = 1/2 × ฐาน × สูง = 1/2 × 8 × 5 = 20",
      hints: ["พื้นที่สามเหลี่ยม = (1/2) × ฐาน × สูง"],
    },
    {
      id: "m1-geo-e5", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "easy",
      question: "มุมฉากมีขนาดเท่าไร?",
      choices: ["45°", "60°", "90°", "180°"],
      answer: 2,
      explanation: "มุมฉากคือมุมที่มีขนาด 90°",
      hints: ["มุมฉากคือ 90 องศา"],
    },
    {
      id: "m1-geo-m1", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "medium",
      question: "สี่เหลี่ยมจัตุรัสมีพื้นที่ 49 ตารางหน่วย ด้านยาวเท่าไร?",
      choices: ["7", "8", "6", "9"],
      answer: 0,
      explanation: "พื้นที่สี่เหลี่ยมจัตุรัส = ด้าน², ด้าน = √49 = 7",
      hints: ["ด้าน² = 49", "ด้าน = √49"],
    },
    {
      id: "m1-geo-m2", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "medium",
      question: "เส้นรอบรูปของสี่เหลี่ยมจัตุรัสที่มีพื้นที่ 36 ตร.หน่วยคือ?",
      choices: ["20", "24", "18", "30"],
      answer: 1,
      explanation: "ด้าน = √36 = 6, เส้นรอบรูป = 4 × 6 = 24",
      hints: ["หาแต่ละด้านก่อน", "ด้าน = √36 = 6", "เส้นรอบรูป = 4 × 6"],
    },
    {
      id: "m1-geo-m3", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "medium",
      question: "มุมภายในของรูปหกเหลี่ยมด้านเท่ามุมละเท่าไร?",
      choices: ["90°", "108°", "120°", "135°"],
      answer: 2,
      explanation: "ผลรวมมุมภายใน = (6-2)×180° = 720°, แต่ละมุม = 720/6 = 120°",
      hints: ["สูตร (n-2)×180°", "(6-2)×180° = 720°", "720°/6 = 120°"],
    },
    {
      id: "m1-geo-m4", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "medium",
      question: "ปริมาตรทรงสี่เหลี่ยมมุมฉาก กว้าง 3 ยาว 4 สูง 5 คือ?",
      choices: ["60", "20", "15", "70"],
      answer: 0,
      explanation: "ปริมาตร = กว้าง × ยาว × สูง = 3 × 4 × 5 = 60",
      hints: ["ปริมาตร = กว้าง × ยาว × สูง"],
    },
    {
      id: "m1-geo-m5", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "medium",
      question: "มุมภายในของรูปห้าเหลี่ยมด้านเท่ามุมละเท่าไร?",
      choices: ["108°", "120°", "90°", "144°"],
      answer: 0,
      explanation: "ผลรวม = (5-2)×180° = 540°, แต่ละมุม = 540/5 = 108°",
      hints: ["(5-2)×180° = 540°", "540°/5"],
    },
    {
      id: "m1-geo-h1", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "hard",
      question: "สามเหลี่ยมมีด้าน 5, 12, 13 เป็นสามเหลี่ยมชนิดใด?",
      choices: ["มุมฉาก", "มุมแหลม", "มุมป้าน", "ด้านเท่า"],
      answer: 0,
      explanation: "5² + 12² = 25 + 144 = 169 = 13² ดังนั้นเป็นสามเหลี่ยมมุมฉาก",
      hints: ["ตรวจสอบ 5² + 12² = 13² หรือไม่"],
    },
    {
      id: "m1-geo-h2", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "hard",
      question: "พื้นที่ผิวของลูกบาศก์ยาวด้านละ 5 หน่วยคือ?",
      choices: ["150", "125", "100", "175"],
      answer: 0,
      explanation: "พื้นที่ผิว = 6 × ด้าน² = 6 × 25 = 150",
      hints: ["ลูกบาศก์มี 6 หน้า", "แต่ละหน้ามีพื้นที่ 5² = 25"],
    },
    {
      id: "m1-geo-h3", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "hard",
      question: "มุมภายในของรูปแปดเหลี่ยมด้านเท่าแต่ละมุมคือ?",
      choices: ["135°", "120°", "150°", "108°"],
      answer: 0,
      explanation: "ผลรวม = (8-2)×180° = 1080°, แต่ละมุม = 1080/8 = 135°",
      hints: ["(8-2)×180° = 1080°", "1080 ÷ 8"],
    },
    {
      id: "m1-geo-h4", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "hard",
      question: "รัศมีของวงกลมที่มีพื้นที่ 49π ตร.หน่วยคือ?",
      choices: ["7", "14", "49", "28"],
      answer: 0,
      explanation: "พื้นที่วงกลม = πr² = 49π, r² = 49, r = 7",
      hints: ["πr² = 49π", "r² = 49"],
    },
    {
      id: "m1-geo-h5", curriculum: "M1", topicId: "m1-basic-geometry", topicName: "เรขาคณิตพื้นฐาน", difficulty: "hard",
      question: "มุมหนึ่งในสามเหลี่ยมมุมฉากเป็น 35° อีกมุมแหลมเป็นเท่าไร?",
      choices: ["55°", "45°", "65°", "35°"],
      answer: 0,
      explanation: "มุมฉาก = 90°, 90 + 35 = 125°, มุมที่สาม = 180 - 125 = 55°",
      hints: ["ผลรวมมุม = 180°", "90° + 35° + x = 180°"],
    },
  ],
  "m1-data-basics": [
    {
      id: "m1-stat-e1", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "easy",
      question: "ค่าเฉลี่ยของ 4, 6, 8, 10 คือ?",
      choices: ["6", "7", "8", "9"],
      answer: 1,
      explanation: "รวม = 28, หาร 4 = 7",
      hints: ["รวมทั้งหมดก่อน", "28 ÷ 4 = 7"],
    },
    {
      id: "m1-stat-e2", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "easy",
      question: "ฐานนิยมของ 2, 3, 3, 5, 7 คือ?",
      choices: ["2", "3", "5", "7"],
      answer: 1,
      explanation: "ฐานนิยมคือค่าที่ปรากฏบ่อยที่สุด = 3",
      hints: ["นับความถี่แต่ละค่า", "3 ปรากฏ 2 ครั้ง"],
    },
    {
      id: "m1-stat-e3", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "easy",
      question: "ค่ามัธยฐานของ 1, 2, 3, 4, 5 คือ?",
      choices: ["1", "2", "3", "5"],
      answer: 2,
      explanation: "ตัวเลขเรียงแล้วค่ากลางคือ 3",
      hints: ["เรียงข้อมูลจากน้อยไปมาก", "หาค่าตรงกลาง"],
    },
    {
      id: "m1-stat-e4", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "easy",
      question: "พิสัยของ 3, 7, 9, 12 คือ?",
      choices: ["6", "9", "12", "15"],
      answer: 1,
      explanation: "พิสัย = สูงสุด - ต่ำสุด = 12 - 3 = 9",
      hints: ["ค่าสูงสุด = 12", "ค่าต่ำสุด = 3"],
    },
    {
      id: "m1-stat-e5", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "easy",
      question: "ความน่าจะเป็นของหัวเมื่อโยนเหรียญคือ?",
      choices: ["0", "1/4", "1/2", "1"],
      answer: 2,
      explanation: "มี 2 ผลลัพธ์เท่าเทียมกัน ดังนั้น 1/2",
      hints: ["ผลลัพธ์ = หัว, ก้อย", "1 ใน 2"],
    },
    {
      id: "m1-stat-m1", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "medium",
      question: "มัธยฐานของ 5, 8, 3, 10, 6 คือ?",
      choices: ["5", "6", "8", "3"],
      answer: 1,
      explanation: "เรียง: 3, 5, 6, 8, 10 ค่ากลาง = 6",
      hints: ["เรียงข้อมูลก่อน", "3, 5, 6, 8, 10"],
    },
    {
      id: "m1-stat-m2", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "medium",
      question: "ค่าเฉลี่ยของ 3, 7, 11, 15 คือ?",
      choices: ["9", "10", "11", "12"],
      answer: 0,
      explanation: "รวม = 36, 36 ÷ 4 = 9",
      hints: ["3 + 7 + 11 + 15 = 36", "36 ÷ 4"],
    },
    {
      id: "m1-stat-m3", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "medium",
      question: "โยนลูกเต๋า 1 ลูก ความน่าจะเป็นได้แต้มคู่คือ?",
      choices: ["1/6", "1/3", "1/2", "2/3"],
      answer: 2,
      explanation: "แต้มคู่ = 2, 4, 6 (3 ค่า), แต้มทั้งหมด = 6, ดังนั้น 3/6 = 1/2",
      hints: ["แต้มคู่มี 2, 4, 6", "3 ค่า จาก 6 ค่า"],
    },
    {
      id: "m1-stat-m4", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "medium",
      question: "ฐานนิยมของ 1, 1, 2, 3, 3, 3, 4 คือ?",
      choices: ["1", "2", "3", "4"],
      answer: 2,
      explanation: "3 ปรากฏ 3 ครั้ง มากที่สุด",
      hints: ["นับความถี่: 1=2, 2=1, 3=3, 4=1"],
    },
    {
      id: "m1-stat-m5", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "medium",
      question: "พิสัยของ 2, 5, 9, 14, 20 คือ?",
      choices: ["18", "16", "20", "14"],
      answer: 0,
      explanation: "20 - 2 = 18",
      hints: ["สูงสุด = 20", "ต่ำสุด = 2"],
    },
    {
      id: "m1-stat-h1", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "hard",
      question: "มัธยฐานของ 4, 6, 8, 10, 12, 14 คือ?",
      choices: ["8", "9", "10", "11"],
      answer: 1,
      explanation: "เรียงแล้ว ข้อมูลคู่ ค่ากลาง = (8+10)/2 = 9",
      hints: ["ข้อมูลมี 6 ตัว (เลขคู่)", "(8+10)/2 = 9"],
    },
    {
      id: "m1-stat-h2", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "hard",
      question: "ถ้าคะแนนสอบ 5 คนคือ 4, 6, 7, 8, x และค่าเฉลี่ยคือ 6 จงหา x",
      choices: ["5", "6", "7", "8"],
      answer: 0,
      explanation: "รวม = 4+6+7+8+x = 25+x, เฉลี่ย = (25+x)/5 = 6, 25+x = 30, x = 5",
      hints: ["รวม = 5 × 6 = 30", "4+6+7+8 = 25", "x = 30-25"],
    },
    {
      id: "m1-stat-h3", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "hard",
      question: "ในถุงมีลูกบอลสีแดง 3 ลูก สีน้ำเงิน 5 ลูก สีเขียว 2 ลูก หยิบ 1 ลูก โอกาสได้สีแดงมีเท่าไร?",
      choices: ["3/10", "3/8", "1/3", "3/7"],
      answer: 0,
      explanation: "ลูกทั้งหมด = 3+5+2 = 10, สีแดง = 3, ดังนั้น 3/10",
      hints: ["หาจำนวนทั้งหมดก่อน", "3+5+2 = 10"],
    },
    {
      id: "m1-stat-h4", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "hard",
      question: "ถ้าข้อมูลชุดหนึ่งมีค่าเฉลี่ย 15 และมัธยฐาน 12 ข้อใดถูกต้อง?",
      choices: ["ข้อมูลเบ้ขวา", "ข้อมูลเบ้ซ้าย", "ข้อมูลสมมาตร", "ข้อมูลปกติ"],
      answer: 0,
      explanation: "ค่าเฉลี่ย > มัธยฐาน แสดงว่าข้อมูลเบ้ขวา (มีค่าสูงดึงค่าเฉลี่ย)",
      hints: ["เฉลี่ย > มัธยฐาน = เบ้ขวา"],
    },
    {
      id: "m1-stat-h5", curriculum: "M1", topicId: "m1-data-basics", topicName: "สถิติเบื้องต้น", difficulty: "hard",
      question: "ผลรวมของข้อมูล 10 จำนวนคือ 200 ถ้าเพิ่มอีกจำนวนหนึ่งเป็น 25 ค่าเฉลี่ยใหม่คือ?",
      choices: ["20.45", "22.5", "20", "25"],
      answer: 0,
      explanation: "รวมใหม่ = 200 + 25 = 225, จำนวนใหม่ = 11, เฉลี่ย = 225/11 = 20.45",
      hints: ["รวมใหม่ = 200 + 25", "225 ÷ 11"],
    },
  ],
}