import type { TopicQuestions } from "./types"

export const M1_QUESTIONS: TopicQuestions = {
  "m1-integers": [
    {
      id: "m1-int-1",
      question: "5 + (-3) เท่ากับอะไร?",
      choices: ["2", "8", "-2", "-8"],
      answer: 0,
      explanation: "บวกจำนวนเต็มลบ คือ ลบจำนวน absolute value: 5 - 3 = 2",
    },
    {
      id: "m1-int-2",
      question: "-4 × (-2) เท่ากับอะไร?",
      choices: ["-8", "8", "-6", "6"],
      answer: 1,
      explanation: "จำนวนลบคูณจำนวนลบได้จำนวนบวก: -4 × -2 = 8",
    },
    {
      id: "m1-int-3",
      question: "10 - 15 เท่ากับอะไร?",
      choices: ["5", "-5", "25", "-25"],
      answer: 1,
      explanation: "10 ลบ 15 ได้ -5",
    },
    {
      id: "m1-int-4",
      question: "-6 ÷ 2 เท่ากับอะไร?",
      choices: ["-3", "3", "-12", "12"],
      answer: 0,
      explanation: "จำนวนลบหารจำนวนบวกได้จำนวนลบ: -6 ÷ 2 = -3",
    },
    {
      id: "m1-int-5",
      question: "(-7) + (+4) เท่ากับอะไร?",
      choices: ["-11", "-3", "3", "11"],
      answer: 1,
      explanation: "จำนวนลบบวกจำนวนบวก: ลบ absolute value: 7 - 4 = 3 แต่เครื่องหมายติดลบ ดังนั้น -3",
    },
  ],
  "m1-exponents": [
    {
      id: "m1-exp-1",
      question: "2^3 เท่ากับอะไร?",
      choices: ["6", "8", "9", "4"],
      answer: 1,
      explanation: "2^3 = 2 × 2 × 2 = 8",
    },
    {
      id: "m1-exp-2",
      question: "5^0 เท่ากับอะไร?",
      choices: ["0", "1", "5", "25"],
      answer: 1,
      explanation: "เลขยกกำลัง 0 ของจำนวนใดๆ (ยกเว้น 0) เท่ากับ 1",
    },
    {
      id: "m1-exp-3",
      question: "3^2 × 3^3 เท่ากับอะไร?",
      choices: ["3^5", "3^6", "9^5", "9^6"],
      answer: 0,
      explanation: "เมื่อคูณเลขยกกำลังที่มีฐานเดียวกัน ให้บวกเลขชี้กำลัง: 3^(2+3) = 3^5",
    },
    {
      id: "m1-exp-4",
      question: "(2^3)^2 เท่ากับอะไร?",
      choices: ["2^5", "2^6", "4^3", "4^5"],
      answer: 1,
      explanation: "เมื่อยกกำลังสอง ให้คูณเลขชี้กำลัง: 2^(3×2) = 2^6",
    },
    {
      id: "m1-exp-5",
      question: "10^4 เท่ากับอะไร?",
      choices: ["1000", "10000", "100000", "40"],
      answer: 1,
      explanation: "10^4 = 10 × 10 × 10 × 10 = 10000",
    },
  ],
  "m1-linear-equations": [
    {
      id: "m1-le-1",
      question: "หาค่า x: 2x + 5 = 15",
      choices: ["x = 5", "x = 10", "x = 7.5", "x = 4"],
      answer: 0,
      explanation: "ลบ 5 จากทั้งสองด้าน: 2x = 10, หารด้วย 2: x = 5",
    },
    {
      id: "m1-le-2",
      question: "หาค่า x: 3x - 7 = 2",
      choices: ["x = 3", "x = 5", "x = -3", "x = 1"],
      answer: 0,
      explanation: "บวก 7: 3x = 9, หารด้วย 3: x = 3",
    },
    {
      id: "m1-le-3",
      question: "หาค่า x: x/4 + 3 = 7",
      choices: ["x = 12", "x = 16", "x = 20", "x = 8"],
      answer: 1,
      explanation: "ลบ 3: x/4 = 4, คูณ 4: x = 16",
    },
    {
      id: "m1-le-4",
      question: "หาค่า x: 5x = 35",
      choices: ["x = 5", "x = 7", "x = 30", "x = 175"],
      answer: 1,
      explanation: "หารทั้งสองด้านด้วย 5: x = 7",
    },
    {
      id: "m1-le-5",
      question: "หาค่า x: 2(x - 3) = 8",
      choices: ["x = 5", "x = 7", "x = 11", "x = -1"],
      answer: 1,
      explanation: "กระจาย: 2x - 6 = 8, บวก 6: 2x = 14, หาร 2: x = 7",
    },
  ],
  "m1-basic-geometry": [
    {
      id: "m1-geo-1",
      question: "ผลรวมมุมภายในของสามเหลี่ยมคือ?",
      choices: ["90°", "180°", "270°", "360°"],
      answer: 1,
      explanation: "มุมภายในสามเหลี่ยมทุกสามมุมมีผลรวม 180°",
    },
    {
      id: "m1-geo-2",
      question: "พื้นที่สี่เหลี่ยมผืนผ้า กว้าง 6 ยาว 9 คือ?",
      choices: ["15", "27", "54", "36"],
      answer: 3,
      explanation: "พื้นที่ = กว้าง × ยาว = 6 × 9 = 54",
    },
    {
      id: "m1-geo-3",
      question: "เส้นรอบวงของวงกลมรัศมี 7 คือ?",
      choices: ["7π", "14π", "21π", "49π"],
      answer: 1,
      explanation: "เส้นรอบวง = 2πr = 2π × 7 = 14π",
    },
    {
      id: "m1-geo-4",
      question: "พื้นที่สามเหลี่ยมฐาน 8 สูง 5 คือ?",
      choices: ["13", "20", "40", "80"],
      answer: 1,
      explanation: "พื้นที่ = 1/2 × ฐาน × สูง = 1/2 × 8 × 5 = 20",
    },
    {
      id: "m1-geo-5",
      question: "มุมฉากมีขนาดเท่าไร?",
      choices: ["45°", "60°", "90°", "180°"],
      answer: 2,
      explanation: "มุมฉากคือมุมที่มีขนาด 90°",
    },
  ],
  "m1-data-basics": [
    {
      id: "m1-stat-1",
      question: "ค่าเฉลี่ยของ 4, 6, 8, 10 คือ?",
      choices: ["6", "7", "8", "9"],
      answer: 2,
      explanation: "รวม = 28, หาร 4 = 7",
    },
    {
      id: "m1-stat-2",
      question: "ฐานนิยมของ 2, 3, 3, 5, 7 คือ?",
      choices: ["2", "3", "5", "7"],
      answer: 1,
      explanation: "ฐานนิยมคือค่าที่ปรากฏบ่อยที่สุด = 3",
    },
    {
      id: "m1-stat-3",
      question: "ค่ามัธยฐานของ 1, 2, 3, 4, 5 คือ?",
      choices: ["1", "2", "3", "5"],
      answer: 2,
      explanation: "ตัวเลขเรียงแล้วค่ากลางคือ 3",
    },
    {
      id: "m1-stat-4",
      question: "ความน่าจะเป็นของหัวเมื่อโยนเหรียญคือ?",
      choices: ["0", "1/4", "1/2", "1"],
      answer: 2,
      explanation: "มี 2 ผลลัพธ์เท่าเทียมกัน ดังนั้น 1/2",
    },
    {
      id: "m1-stat-5",
      question: "พิสัยของ 3, 7, 9, 12 คือ?",
      choices: ["6", "9", "12", "15"],
      answer: 1,
      explanation: "พิสัย = สูงสุด - ต่ำสุด = 12 - 3 = 9",
    },
  ],
}