import type { TopicQuestions } from "./types"

export const M2_QUESTIONS: TopicQuestions = {
  "m2-polynomials": [
    {
      id: "m2-poly-e1", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "easy",
      question: "(x + 3) + (2x - 5) เท่ากับ?",
      choices: ["3x - 2", "3x + 2", "x - 2", "x + 8"],
      answer: 0,
      explanation: "รวมพจน์ที่เหมือนกัน: x + 2x = 3x, 3 - 5 = -2",
      hints: ["รวมพจน์ x ก่อน", "แล้วรวมค่าคงที่"],
    },
    {
      id: "m2-poly-e2", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "easy",
      question: "(x + 2)(x + 3) เท่ากับ?",
      choices: ["x² + 5x + 6", "x² + 6x + 5", "x² + 5", "2x + 5"],
      answer: 0,
      explanation: "ใช้ FOIL: x² + 3x + 2x + 6 = x² + 5x + 6",
      hints: ["คูณหน้าคูณหน้า = x²", "คูณนอก = 3x", "คูณใน = 2x", "คูณหลัง = 6"],
    },
    {
      id: "m2-poly-e3", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "easy",
      question: "(2x + 1)(x - 3) เท่ากับ?",
      choices: ["2x² - 5x - 3", "2x² + 5x - 3", "2x² - 7x - 3", "2x² - x - 3"],
      answer: 0,
      explanation: "FOIL: 2x² - 6x + x - 3 = 2x² - 5x - 3",
      hints: ["2x × x = 2x²", "2x × (-3) = -6x", "1 × x = x"],
    },
    {
      id: "m2-poly-e4", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "easy",
      question: "พหุนาม 3x + 2 มีกี่พจน์?",
      choices: ["1", "2", "3", "4"],
      answer: 1,
      explanation: "3x และ 2 รวม 2 พจน์",
      hints: ["พจน์คือส่วนที่คั่นด้วย + หรือ -"],
    },
    {
      id: "m2-poly-e5", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "easy",
      question: "ดีกรีของพหุนาม 2x³ - x² + 5 คือ?",
      choices: ["1", "2", "3", "5"],
      answer: 2,
      explanation: "ดีกรีสูงสุดของพหุนามคือ 3 (จาก x³)",
      hints: ["ดีกรีคือเลขชี้กำลังสูงสุด"],
    },
    {
      id: "m2-poly-m1", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "medium",
      question: "(3x - 1)(x + 2) เท่ากับ?",
      choices: ["3x² + 5x - 2", "3x² + 7x - 2", "3x² + 7x + 2", "3x² - 5x - 2"],
      answer: 0,
      explanation: "FOIL: 3x² + 6x - x - 2 = 3x² + 5x - 2",
      hints: ["3x × x = 3x²", "3x × 2 = 6x", "-1 × x = -x"],
    },
    {
      id: "m2-poly-m2", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "medium",
      question: "ลดรูป: (x + 3)(x - 3) เท่ากับ?",
      choices: ["x² - 9", "x² + 9", "x² - 6x + 9", "x² + 6x - 9"],
      answer: 0,
      explanation: "(x + 3)(x - 3) = x² - 3x + 3x - 9 = x² - 9",
      hints: ["พจน์กลางตัดกัน", "เป็นผลต่างกำลังสอง"],
    },
    {
      id: "m2-poly-m3", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "medium",
      question: "(x + 4)² เท่ากับ?",
      choices: ["x² + 16x + 16", "x² + 8x + 16", "x² + 4x + 8", "x² + 16"],
      answer: 1,
      explanation: "(x + 4)² = x² + 2(4)x + 16 = x² + 8x + 16",
      hints: ["(a+b)² = a² + 2ab + b²"],
    },
    {
      id: "m2-poly-m4", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "medium",
      question: "(x - 5)² เท่ากับ?",
      choices: ["x² - 10x + 25", "x² + 10x + 25", "x² - 25", "x² + 25"],
      answer: 0,
      explanation: "(x - 5)² = x² - 10x + 25",
      hints: ["(a-b)² = a² - 2ab + b²"],
    },
    {
      id: "m2-poly-m5", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "medium",
      question: "(2x - 3)² เท่ากับ?",
      choices: ["4x² - 12x + 9", "4x² + 12x + 9", "2x² - 6x + 9", "4x² - 9"],
      answer: 0,
      explanation: "(2x - 3)² = 4x² - 12x + 9",
      hints: ["(2x)² = 4x²", "2(2x)(-3) = -12x"],
    },
    {
      id: "m2-poly-h1", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "hard",
      question: "(x + 1)(x - 2)(x + 3) เท่ากับ?",
      choices: ["x³ + 2x² - 5x - 6", "x³ + 2x² + 5x + 6", "x³ - 2x² - 5x + 6", "x³ + x² - 5x - 6"],
      answer: 0,
      explanation: "(x+1)(x-2)=x²-x-2, (x²-x-2)(x+3)=x³+3x²-x²-3x-2x-6=x³+2x²-5x-6",
      hints: ["คูณสองพจน์แรกก่อน", "แล้วคูณกับพจน์ที่สาม"],
    },
    {
      id: "m2-poly-h2", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "hard",
      question: "ถ้า (x + a)(x + b) = x² + 7x + 12 แล้ว a + b เท่ากับ?",
      choices: ["7", "12", "3", "4"],
      answer: 0,
      explanation: "a+b = 7 (สัมประสิทธิ์ของ x), ab = 12 (ค่าคงที่)",
      hints: ["(x+a)(x+b) = x² + (a+b)x + ab"],
    },
    {
      id: "m2-poly-h3", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "hard",
      question: "ดีกรีของพหุนาม (x² + 1)(x³ - 2x + 1) คือ?",
      choices: ["5", "6", "3", "2"],
      answer: 0,
      explanation: "x² × x³ = x⁵ ดังนั้นดีกรี 5",
      hints: ["รวมดีกรีของพจน์สูงสุด", "2 + 3 = 5"],
    },
    {
      id: "m2-poly-h4", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "hard",
      question: "(2x + 3)(x - 1) - (x + 2)(x - 3) เท่ากับ?",
      choices: ["x² + 6x + 3", "x² + 3", "x² + 2x - 3", "x² + 6x - 3"],
      answer: 0,
      explanation: "= (2x²+3x-2x-3) - (x²+2x-3x-6) = (2x²+x-3) - (x²-x-6) = x²+2x+3",
      hints: ["กระจายทั้งสองวงเล็บก่อน", "ระวังเครื่องหมายลบ"],
    },
    {
      id: "m2-poly-h5", curriculum: "M2", topicId: "m2-polynomials", topicName: "พหุนาม", difficulty: "hard",
      question: "สัมประสิทธิ์ของ x² ใน (2x - 1)(x² + 3x - 2) คือ?",
      choices: ["5", "-1", "3", "1"],
      answer: 0,
      explanation: "2x × 3x = 6x², (-1) × x² = -x², รวม = 5x²",
      hints: ["หาพจน์ที่คูณกันแล้วได้ x²", "2x × 3x = 6x²", "-1 × x² = -x²"],
    },
  ],
  "m2-factoring": [
    {
      id: "m2-fact-e1", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "easy",
      question: "แยกตัวประกอบ: x² - 9",
      choices: ["(x+3)(x+3)", "(x-3)(x-3)", "(x+3)(x-3)", "(x+9)(x-1)"],
      answer: 2,
      explanation: "ผลต่างกำลังสอง: a² - b² = (a+b)(a-b)",
      hints: ["x² = (x)²", "9 = 3²"],
    },
    {
      id: "m2-fact-e2", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "easy",
      question: "แยกตัวประกอบ: x² + 7x + 12",
      choices: ["(x+3)(x+4)", "(x+2)(x+6)", "(x+1)(x+12)", "(x-3)(x-4)"],
      answer: 0,
      explanation: "สองจำนวนที่คูณกันได้ 12 และบวกกันได้ 7 คือ 3 และ 4",
      hints: ["หา 2 จำนวนที่คูณได้ 12", "และบวกได้ 7"],
    },
    {
      id: "m2-fact-e3", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "easy",
      question: "แยกตัวประกอบ: x² - 16",
      choices: ["(x-4)(x-4)", "(x+4)(x+4)", "(x+4)(x-4)", "(x-8)(x+2)"],
      answer: 2,
      explanation: "ผลต่างกำลังสอง: x² - 4² = (x+4)(x-4)",
      hints: ["16 = 4²", "ใช้สูตรผลต่างกำลังสอง"],
    },
    {
      id: "m2-fact-e4", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "easy",
      question: "แยกตัวประกอบ: x² + 5x + 6",
      choices: ["(x+2)(x+3)", "(x+1)(x+6)", "(x-2)(x-3)", "(x+2)(x-3)"],
      answer: 0,
      explanation: "2 × 3 = 6, 2 + 3 = 5",
      hints: ["หา 2 จำนวนที่คูณได้ 6", "และบวกได้ 5"],
    },
    {
      id: "m2-fact-e5", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "easy",
      question: "แยกตัวประกอบ: x² - 4",
      choices: ["(x-2)(x-2)", "(x+2)(x+2)", "(x+2)(x-2)", "(x-4)(x+1)"],
      answer: 2,
      explanation: "x² - 2² = (x+2)(x-2)",
      hints: ["4 = 2²", "ใช้ผลต่างกำลังสอง"],
    },
    {
      id: "m2-fact-m1", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "medium",
      question: "แยกตัวประกอบ: x² + 8x + 16",
      choices: ["(x+4)(x+4)", "(x+8)(x+2)", "(x-4)(x-4)", "(x+8)(x-2)"],
      answer: 0,
      explanation: "เป็นกำลังสองสมบูรณ์: (x+4)² = x² + 8x + 16",
      hints: ["16 = 4²", "2(4) = 8"],
    },
    {
      id: "m2-fact-m2", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "medium",
      question: "แยกตัวประกอบ: x² - 6x + 9",
      choices: ["(x-3)(x-3)", "(x+3)(x+3)", "(x-9)(x+1)", "(x-3)(x+3)"],
      answer: 0,
      explanation: "เป็นกำลังสองสมบูรณ์: (x-3)² = x² - 6x + 9",
      hints: ["9 = 3²", "2(3) = 6"],
    },
    {
      id: "m2-fact-m3", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "medium",
      question: "แยกตัวประกอบ: x² - x - 12",
      choices: ["(x-4)(x+3)", "(x+4)(x-3)", "(x-2)(x+6)", "(x+2)(x-6)"],
      answer: 0,
      explanation: "-4 × 3 = -12, -4 + 3 = -1",
      hints: ["หา 2 จำนวนที่คูณได้ -12", "และบวกได้ -1"],
    },
    {
      id: "m2-fact-m4", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "medium",
      question: "แยกตัวประกอบ: x² + 2x - 15",
      choices: ["(x+5)(x-3)", "(x-5)(x+3)", "(x+1)(x-15)", "(x+5)(x+3)"],
      answer: 0,
      explanation: "5 × (-3) = -15, 5 + (-3) = 2",
      hints: ["หา 2 จำนวนที่คูณได้ -15", "และบวกได้ 2"],
    },
    {
      id: "m2-fact-m5", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "medium",
      question: "แยกตัวประกอบ: 2x² + 6x",
      choices: ["2x(x+3)", "x(2x+6)", "2(x²+3x)", "2x(x+6)"],
      answer: 0,
      explanation: "ดึงตัวร่วม 2x: 2x(x + 3)",
      hints: ["หา ตัวหารร่วมมากของ 2x² และ 6x", "2x เป็นตัวร่วม"],
    },
    {
      id: "m2-fact-h1", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "hard",
      question: "แยกตัวประกอบ: 3x² + 10x + 8",
      choices: ["(3x+4)(x+2)", "(3x+2)(x+4)", "(x+2)(3x+8)", "(3x+1)(x+8)"],
      answer: 0,
      explanation: "3x² + 6x + 4x + 8 = 3x(x+2) + 4(x+2) = (3x+4)(x+2)",
      hints: ["แยกพจน์กลาง 10x = 6x+4x", "จับคู่และดึงตัวร่วม"],
    },
    {
      id: "m2-fact-h2", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "hard",
      question: "แยกตัวประกอบ: 6x² - 11x - 10",
      choices: ["(3x+2)(2x-5)", "(3x-5)(2x+2)", "(6x+1)(x-10)", "(2x+5)(3x-2)"],
      answer: 0,
      explanation: "6x² - 15x + 4x - 10 = 3x(2x-5) + 2(2x-5) = (3x+2)(2x-5)",
      hints: ["แยก -11x = -15x+4x", "จับคู่และดึงตัวร่วม"],
    },
    {
      id: "m2-fact-h3", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "hard",
      question: "แยกตัวประกอบ: x⁴ - 16",
      choices: ["(x²+4)(x+2)(x-2)", "(x²-4)(x²+4)", "(x²-4)(x²-4)", "(x²+4)(x²+4)"],
      answer: 0,
      explanation: "x⁴ - 16 = (x²-4)(x²+4) = (x-2)(x+2)(x²+4)",
      hints: ["แยกเป็น (x²)² - 4²", "แล้วแยก x²-4 ต่อ"],
    },
    {
      id: "m2-fact-h4", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "hard",
      question: "แยกตัวประกอบ: 4x² - 12x + 9",
      choices: ["(2x-3)(2x-3)", "(2x+3)(2x+3)", "(x-3)(4x-3)", "(2x-9)(2x-1)"],
      answer: 0,
      explanation: "(2x)² = 4x², 2(2x)(-3) = -12x, (-3)² = 9",
      hints: ["เป็นกำลังสองสมบูรณ์", "ตรวจสอบ (2x-3)²"],
    },
    {
      id: "m2-fact-h5", curriculum: "M2", topicId: "m2-factoring", topicName: "การแยกตัวประกอบ", difficulty: "hard",
      question: "แยกตัวประกอบ: x² + 6x - 27",
      choices: ["(x+9)(x-3)", "(x-9)(x+3)", "(x+6)(x-9)", "(x-6)(x+9)"],
      answer: 0,
      explanation: "9 × (-3) = -27, 9 + (-3) = 6",
      hints: ["หา 2 จำนวนที่คูณได้ -27", "และบวกได้ 6"],
    },
  ],
  "m2-pythagorean": [
    {
      id: "m2-pyth-e1", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "easy",
      question: "สามเหลี่ยมมุมฉาก a=3, b=4 ด้าน c (ตรงข้ามมุมฉาก) คือ?",
      choices: ["5", "6", "7", "8"],
      answer: 0,
      explanation: "a² + b² = c²: 9 + 16 = 25, c = √25 = 5",
      hints: ["3² = 9", "4² = 16", "9+16 = 25"],
    },
    {
      id: "m2-pyth-e2", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "easy",
      question: "สามเหลี่ยมมุมฉาก a=5, c=13 ขนาด b คือ?",
      choices: ["8", "10", "12", "15"],
      answer: 2,
      explanation: "b² = c² - a² = 169 - 25 = 144, b = √144 = 12",
      hints: ["c² = 169", "a² = 25", "169 - 25 = 144"],
    },
    {
      id: "m2-pyth-e3", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "easy",
      question: "สามเหลี่ยมมุมฉาก a=6, b=8 หา c?",
      choices: ["10", "12", "14", "16"],
      answer: 0,
      explanation: "6² + 8² = 36 + 64 = 100, c = √100 = 10",
      hints: ["6² = 36", "8² = 64"],
    },
    {
      id: "m2-pyth-e4", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "easy",
      question: "ด้านตรงข้ามมุมฉากคือด้านใด?",
      choices: ["ด้านที่ยาวที่สุด", "ด้านที่สั้นที่สุด", "ด้านที่ยาวเท่ากัน", "ทุกด้าน"],
      answer: 0,
      explanation: "ด้านตรงข้ามมุมฉากคือด้านที่ยาวที่สุดในสามเหลี่ยมมุมฉาก",
      hints: ["อยู่ตรงข้ามมุมฉาก"],
    },
    {
      id: "m2-pyth-e5", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "easy",
      question: "สามเหลี่ยมด้าน 9, 12, 15 เป็นสามเหลี่ยมมุมฉากหรือไม่?",
      choices: ["ใช่", "ไม่ใช่", "ไม่แน่ชัด", "เป็นสามเหลี่ยมด้านเท่า"],
      answer: 0,
      explanation: "9² + 12² = 81 + 144 = 225 = 15²",
      hints: ["81 + 144 = 225"],
    },
    {
      id: "m2-pyth-m1", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "medium",
      question: "บันไดยาว 13 ฟุต พิงผนัง ฐานห่างจากผนัง 5 ฟุต ปลายบันไดสูงจากพื้นเท่าไร?",
      choices: ["12", "10", "15", "8"],
      answer: 0,
      explanation: "h² = 13² - 5² = 169 - 25 = 144, h = 12",
      hints: ["c = 13, a = 5", "b² = 169 - 25 = 144"],
    },
    {
      id: "m2-pyth-m2", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "medium",
      question: "สี่เหลี่ยมผืนผ้ากว้าง 8 ยาว 15 เส้นทแยงมุมยาวเท่าไร?",
      choices: ["17", "18", "19", "20"],
      answer: 0,
      explanation: "d² = 8² + 15² = 64 + 225 = 289, d = 17",
      hints: ["เส้นทแยงมุม = ด้านตรงข้ามมุมฉาก"],
    },
    {
      id: "m2-pyth-m3", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "medium",
      question: "สามเหลี่ยมมุมฉาก a=7, b=24 หา c?",
      choices: ["25", "26", "27", "28"],
      answer: 0,
      explanation: "7² + 24² = 49 + 576 = 625, c = √625 = 25",
      hints: ["49 + 576 = 625"],
    },
    {
      id: "m2-pyth-m4", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "medium",
      question: "สามเหลี่ยมด้าน 20, 21, 29 เป็นสามเหลี่ยมมุมฉากหรือไม่?",
      choices: ["ใช่", "ไม่ใช่", "ไม่แน่ชัด", "เป็นสามเหลี่ยมด้านเท่า"],
      answer: 0,
      explanation: "20² + 21² = 400 + 441 = 841 = 29²",
      hints: ["400 + 441 = 841"],
    },
    {
      id: "m2-pyth-m5", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "medium",
      question: "สามเหลี่ยมมุมฉาก a=8, c=17 หา b?",
      choices: ["15", "12", "10", "18"],
      answer: 0,
      explanation: "b² = 289 - 64 = 225, b = 15",
      hints: ["17² = 289", "8² = 64"],
    },
    {
      id: "m2-pyth-h1", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "hard",
      question: "สามเหลี่ยมด้าน 5, 12, 13 ความยาวรอบรูปคือ?",
      choices: ["30", "26", "28", "32"],
      answer: 0,
      explanation: "เส้นรอบรูป = 5 + 12 + 13 = 30",
      hints: ["รวมความยาวทั้งสามด้าน"],
    },
    {
      id: "m2-pyth-h2", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "hard",
      question: "สี่เหลี่ยมจัตุรัสมีเส้นทแยงมุมยาว 10√2 หน่วย ด้านยาวเท่าไร?",
      choices: ["10", "5", "20", "15"],
      answer: 0,
      explanation: "d² = a² + a² = 2a², (10√2)² = 2a², 200 = 2a², a² = 100, a = 10",
      hints: ["เส้นทแยงมุม = a√2"],
    },
    {
      id: "m2-pyth-h3", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "hard",
      question: "สามเหลี่ยมมุมฉากมีด้านประกอบมุมฉากยาว a และ a+1 ด้านตรงข้ามมุมฉากยาว 5 หาค่า a",
      choices: ["3", "4", "5", "2"],
      answer: 0,
      explanation: "a² + (a+1)² = 25, a² + a² + 2a + 1 = 25, 2a² + 2a - 24 = 0, a² + a - 12 = 0, (a+4)(a-3)=0, a=3",
      hints: ["a² + (a+1)² = 25", "แยกตัวประกอบ"],
    },
    {
      id: "m2-pyth-h4", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "hard",
      question: "สามเหลี่ยมมุมฉากมีพื้นที่ 30 ตารางหน่วย ด้านประกอบมุมฉากยาว 5 และ b หน่วย หา b",
      choices: ["12", "10", "8", "15"],
      answer: 0,
      explanation: "พื้นที่ = 1/2 × 5 × b = 30, 5b/2 = 30, 5b = 60, b = 12",
      hints: ["พื้นที่สามเหลี่ยมมุมฉาก = 1/2 × ผลคูณด้านประกอบมุมฉาก"],
    },
    {
      id: "m2-pyth-h5", curriculum: "M2", topicId: "m2-pythagorean", topicName: "ทฤษฎีพีทาโกรัส", difficulty: "hard",
      question: "ระยะห่างระหว่างจุด (0,0) กับ (5,12) คือ?",
      choices: ["13", "17", "15", "10"],
      answer: 0,
      explanation: "d² = (5-0)² + (12-0)² = 25 + 144 = 169, d = 13",
      hints: ["ใช้ทฤษฎีพีทาโกรัสในระบบพิกัด"],
    },
  ],
  "m2-probability": [
    {
      id: "m2-prob-e1", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "easy",
      question: "โยนลูกเต๋า 1 ลูก ความน่าจะเป็นได้แต้ม 1 คือ?",
      choices: ["1/6", "1/12", "1/3", "1/2"],
      answer: 0,
      explanation: "มี 6 หน้า โอกาสได้แต้ม 1 คือ 1 ใน 6",
      hints: ["ลูกเต๋ามี 6 หน้า"],
    },
    {
      id: "m2-prob-e2", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "easy",
      question: "ถุงมีลูกบอลสีแดง 3 ลูก สีน้ำเงิน 2 ลูก หยิบ 1 ลูก ความน่าจะเป็นได้สีแดงคือ?",
      choices: ["3/5", "2/5", "1/2", "2/3"],
      answer: 0,
      explanation: "ลูกทั้งหมด 5 ลูก สีแดง 3 ลูก ดังนั้น 3/5",
      hints: ["จำนวนทั้งหมด = 3+2 = 5"],
    },
    {
      id: "m2-prob-e3", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "easy",
      question: "ความน่าจะเป็นของเหตุการณ์ที่แน่นอนคือ?",
      choices: ["0", "0.5", "1", "Infinity"],
      answer: 2,
      explanation: "เหตุการณ์ที่แน่นอนมีความน่าจะเป็น 1",
      hints: ["เหตุการณ์ที่เกิดขึ้นแน่นอน = 1"],
    },
    {
      id: "m2-prob-e4", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "easy",
      question: "ความน่าจะเป็นของเหตุการณ์ที่เป็นไปไม่ได้คือ?",
      choices: ["0", "0.5", "1", "-1"],
      answer: 0,
      explanation: "เหตุการณ์ที่เป็นไปไม่ได้มีความน่าจะเป็น 0",
      hints: ["เหตุการณ์ที่เกิดขึ้นไม่ได้ = 0"],
    },
    {
      id: "m2-prob-e5", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "easy",
      question: "ในกล่องมีปากกา 4 ด้าม สีดำ 2 ด้าม สีแดง 2 ด้าม หยิบ 1 ด้าม โอกาสได้สีดำคือ?",
      choices: ["1/2", "1/4", "2/4", "1/3"],
      answer: 0,
      explanation: "ปากกาทั้งหมด 4 ด้าม สีดำ 2 ด้าม = 2/4 = 1/2",
      hints: ["2 ใน 4 = 1/2"],
    },
    {
      id: "m2-prob-m1", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "medium",
      question: "โยนเหรียญ 2 ครั้ง ความน่าจะเป็นได้หัวทั้งคู่คือ?",
      choices: ["1/2", "1/4", "3/4", "1/8"],
      answer: 1,
      explanation: "ผลลัพธ์ทั้งหมด 4 ค่า (HH, HT, TH, TT) ได้ HH 1 ค่า = 1/4",
      hints: ["เขียนแผนภาพต้นไม้", "HH, HT, TH, TT"],
    },
    {
      id: "m2-prob-m2", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "medium",
      question: "โยนลูกเต๋า 1 ลูก ความน่าจะเป็นได้แต้มน้อยกว่า 3 คือ?",
      choices: ["1/3", "1/2", "2/3", "1/6"],
      answer: 0,
      explanation: "แต้มน้อยกว่า 3 = 1, 2 รวม 2 ค่า, 2/6 = 1/3",
      hints: ["แต้ม 1, 2 มีกี่ค่า? = 2 ค่า", "2/6"],
    },
    {
      id: "m2-prob-m3", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "medium",
      question: "จากตัวอักษร A, B, C, D สุ่มเลือก 1 ตัว ความน่าจะเป็นได้สระคือ?",
      choices: ["1/4", "1/2", "3/4", "1/8"],
      answer: 0,
      explanation: "มีสระคือ A เท่านั้น 1 ตัว จาก 4 ตัว = 1/4",
      hints: ["สระมีตัวเดียวคือ A"],
    },
    {
      id: "m2-prob-m4", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "medium",
      question: "โยนลูกเต๋า 2 ลูกพร้อมกัน จำนวนผลลัพธ์ทั้งหมดคือ?",
      choices: ["36", "12", "6", "18"],
      answer: 0,
      explanation: "ลูกเต๋าแต่ละลูกมี 6 หน้า ดังนั้น 6 × 6 = 36",
      hints: ["6 × 6 = 36"],
    },
    {
      id: "m2-prob-m5", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "medium",
      question: "หยิบไพ่ 1 ใบจากไพ่ 52 ใบ ความน่าจะเป็นได้โพดำคือ?",
      choices: ["1/4", "1/13", "1/52", "1/2"],
      answer: 0,
      explanation: "โพดำมี 13 ใบ จาก 52 ใบ = 13/52 = 1/4",
      hints: ["ไพ่มี 4 ชุด", "ชุดละ 13 ใบ"],
    },
    {
      id: "m2-prob-h1", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "hard",
      question: "โยนเหรียญ 3 ครั้ง ความน่าจะเป็นได้หัวอย่างน้อย 1 ครั้งคือ?",
      choices: ["7/8", "1/8", "3/8", "5/8"],
      answer: 0,
      explanation: "ไม่หัวเลย = 1/8, ดังนั้นหัวอย่างน้อย 1 = 1 - 1/8 = 7/8",
      hints: ["ใช้ complement", "1 - P(ไม่หัวเลย)"],
    },
    {
      id: "m2-prob-h2", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "hard",
      question: "ในถุงมีลูกแก้ว 4 สีแดง 6 สีเขียว หยิบ 2 ลูกพร้อมกัน ความน่าจะเป็นได้สีแดงทั้งคู่คือ?",
      choices: ["6/45", "4/10", "2/9", "1/5"],
      answer: 0,
      explanation: "หยิบ 2 จาก 10 = 45 วิธี, หยิบ 2 จาก 4 = 6 วิธี, = 6/45",
      hints: ["ใช้组合", "C(10,2) = 45, C(4,2) = 6"],
    },
    {
      id: "m2-prob-h3", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "hard",
      question: "โยนลูกเต๋า 2 ลูก ความน่าจะเป็นได้ผลรวมเป็น 7 คือ?",
      choices: ["1/6", "1/12", "1/9", "1/36"],
      answer: 0,
      explanation: "คู่ที่รวมเป็น 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6/36 = 1/6",
      hints: ["นับคู่ที่รวมกันได้ 7"],
    },
    {
      id: "m2-prob-h4", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "hard",
      question: "ไพ่ 52 ใบ หยิบ 1 ใบ ความน่าจะเป็นได้ A หรือ K คือ?",
      choices: ["2/13", "1/13", "2/52", "4/13"],
      answer: 0,
      explanation: "A มี 4 ใบ, K มี 4 ใบ รวม 8 ใบ, 8/52 = 2/13",
      hints: ["A = 4 ใบ", "K = 4 ใบ", "รวม 8 ใบ"],
    },
    {
      id: "m2-prob-h5", curriculum: "M2", topicId: "m2-probability", topicName: "ความน่าจะเป็น", difficulty: "hard",
      question: "ความน่าจะเป็นที่วันเกิดของคน 2 คนตรงกันคือ? (ไม่考虑 leap year)",
      choices: ["1/365", "1/730", "364/365", "1/366"],
      answer: 0,
      explanation: "คนแรกเกิดวันไหนก็ได้, คนที่สองต้องเกิดวันเดียวกัน = 1/365",
      hints: ["365 วันใน 1 ปี"],
    },
  ],
}