import type { TopicQuestions } from "./types"

export const M2_QUESTIONS: TopicQuestions = {
  "m2-polynomials": [
    {
      id: "m2-poly-1",
      question: "(x + 3) + (2x - 5) เท่ากับ?",
      choices: ["3x - 2", "3x + 2", "x - 2", "x + 8"],
      answer: 0,
      explanation: "รวมพจน์ที่เหมือนกัน: x + 2x = 3x, 3 - 5 = -2",
    },
    {
      id: "m2-poly-2",
      question: "(x + 2)(x + 3) เท่ากับ?",
      choices: ["x^2 + 5x + 6", "x^2 + 6x + 5", "x^2 + 5", "2x + 5"],
      answer: 0,
      explanation: "ใช้ FOIL: x² + 3x + 2x + 6 = x² + 5x + 6",
    },
    {
      id: "m2-poly-3",
      question: "x^2 - 4x + 4 แยกตัวประกอบได้?",
      choices: ["(x-2)(x-2)", "(x+2)(x+2)", "(x-4)(x+1)", "(x-1)(x+4)"],
      answer: 0,
      explanation: "นี้เป็นผลต่างของกำลังสอง: (x-2)²",
    },
    {
      id: "m2-poly-4",
      question: "(2x + 1)(x - 3) เท่ากับ?",
      choices: ["2x^2 - 5x - 3", "2x^2 + 5x - 3", "2x^2 - 7x - 3", "2x^2 - x - 3"],
      answer: 0,
      explanation: "FOIL: 2x² - 6x + x - 3 = 2x² - 5x - 3",
    },
    {
      id: "m2-poly-5",
      question: "x^3 - x^2 + 2x เป็นพหุนามดีกรี?",
      choices: ["1", "2", "3", "4"],
      answer: 2,
      explanation: "ดีกรีสูงสุดของพหุนามคือ 3 (จาก x³)",
    },
  ],
  "m2-factoring": [
    {
      id: "m2-fact-1",
      question: "แยกตัวประกอบ: x^2 - 9",
      choices: ["(x+3)(x+3)", "(x-3)(x-3)", "(x+3)(x-3)", "(x+9)(x-1)"],
      answer: 2,
      explanation: "ผลต่างกำลังสอง: a² - b² = (a+b)(a-b)",
    },
    {
      id: "m2-fact-2",
      question: "แยกตัวประกอบ: x^2 + 7x + 12",
      choices: ["(x+3)(x+4)", "(x+2)(x+6)", "(x+1)(x+12)", "(x-3)(x-4)"],
      answer: 0,
      explanation: "หาร 12 เป็นจำนวนเต็ม: 3 × 4 = 12, 3 + 4 = 7",
    },
    {
      id: "m2-fact-3",
      question: "แยกตัวประกอบ: 2x^2 + 5x + 3",
      choices: ["(2x+1)(x+3)", "(2x+3)(x+1)", "(x+2)(2x+3)", "(2x-1)(x-3)"],
      answer: 1,
      explanation: "ใช้วิธีการแยกตัวประกอบax² + bx + c",
    },
    {
      id: "m2-fact-4",
      question: "x^2 - 16 แยกตัวประกอบได้?",
      choices: ["(x-4)(x-4)", "(x+4)(x+4)", "(x+4)(x-4)", "(x-8)(x+2)"],
      answer: 2,
      explanation: "ผลต่างกำลังสอง: x² - 4² = (x+4)(x-4)",
    },
    {
      id: "m2-fact-5",
      question: "แยกตัวประกอบ: 3x^2 - 12",
      choices: ["3(x-2)(x+2)", "3(x-4)(x+4)", "(3x-12)(x+1)", "3(x²-4)"],
      answer: 3,
      explanation: "เอาตัวประกอบร่วม: 3(x² - 4)",
    },
  ],
  "m2-pythagorean": [
    {
      id: "m2-pyth-1",
      question: "สามเหลี่ยมมุมฉาก a=3, b=4 ด้าน c คือ?",
      choices: ["5", "6", "7", "8"],
      answer: 0,
      explanation: "a² + b² = c²: 9 + 16 = 25, c = 5",
    },
    {
      id: "m2-pyth-2",
      question: "สามเหลี่ยมมุมฉาก a=5, c=13 ขนาด b คือ?",
      choices: ["8", "10", "12", "15"],
      answer: 2,
      explanation: "b² = c² - a² = 169 - 25 = 144, b = 12",
    },
    {
      id: "m2-pyth-3",
      question: "เส้นตรงยาว 25 วัดจากพื้น 7 ด้านสูงคือ?",
      choices: ["20", "22", "24", "26"],
      answer: 2,
      explanation: "h² = 25² - 7² = 625 - 49 = 576, h = 24",
    },
    {
      id: "m2-pyth-4",
      question: "สามเหลี่ยมด้าน 6, 8, 10 เป็นมุมฉากหรือไม่?",
      choices: ["ใช่", "ไม่ใช่", "ไม่สามารถบอกได้", "เป็นมุมแหลม"],
      answer: 0,
      explanation: "6² + 8² = 36 + 64 = 100 = 10²",
    },
    {
      id: "m2-pyth-5",
      question: "ด้านตรงข้ามมุมฉากเรียกว่าอะไร?",
      choices: ["ด้านประกอบ", "ด้านตรงข้าม", "ด้านใกล้", "ด้านยาว"],
      answer: 1,
      explanation: "ด้านตรงข้ามมุมฉากเรียกว่า ด้านตรงข้าม (hypotenuse)",
    },
  ],
  "m2-probability": [
    {
      id: "m2-prob-1",
      question: "โยนลูกเต๋า ความน่าจะเป็นได้ 6 คือ?",
      choices: ["1/6", "1/12", "1/3", "1/2"],
      answer: 0,
      explanation: "ผลลัพธ์ที่เป็นไปได้ 6 ค่า ดังนั้น 1/6",
    },
    {
      id: "m2-prob-2",
      question: "ถุงมี 3 ลูกสีแดง 2 ลูกสีน้ำเงิน ดึงลูกสีแดงคือ?",
      choices: ["3/5", "2/5", "1/2", "2/3"],
      answer: 0,
      explanation: "ลูกทั้งหมด 5 ลูก สีแดง 3 ลูก ดังนั้น 3/5",
    },
    {
      id: "m2-prob-3",
      question: "ความน่าจะเป็นของเหตุการณ์ที่แน่นอนคือ?",
      choices: ["0", "0.5", "1", "Infinity"],
      answer: 2,
      explanation: "เหตุการณ์ที่แน่นอนมีความน่าจะเป็น 1",
    },
    {
      id: "m2-prob-4",
      question: "โยนเหรียญ 2 ครั้ง ความน่าจะเป็นได้หัวทั้งคู่คือ?",
      choices: ["1/2", "1/4", "3/4", "1/8"],
      answer: 1,
      explanation: "ผลลัพธ์ทั้งหมด 4 ค่า (HH, HT, TH, TT) ได้ HH 1 ค่า",
    },
    {
      id: "m2-prob-5",
      question: "ความน่าจะเป็นของเหตุการณ์ที่เป็นไปไม่ได้คือ?",
      choices: ["0", "0.5", "1", "-1"],
      answer: 0,
      explanation: "เหตุการณ์ที่เป็นไปไม่ได้มีความน่าจะเป็น 0",
    },
  ],
}