import type { TopicQuestions } from "./types"

export const M3_QUESTIONS: TopicQuestions = {
  "m3-quadratics": [
    {
      id: "m3-quad-1",
      question: "รากของสมการ x^2 - 5x + 6 = 0 คือ?",
      choices: ["x = 2, 3", "x = -2, -3", "x = 1, 6", "x = -1, -6"],
      answer: 0,
      explanation: "แยกตัวประกอบ: (x-2)(x-3) = 0, ดังนั้น x = 2 หรือ x = 3",
    },
    {
      id: "m3-quad-2",
      question: "สมการ x^2 + 4x + 4 = 0 มีรากเดียวหรือไม่?",
      choices: ["ใช่", "ไม่ใช่", "ไม่มีราก", "มี 2 ราก"],
      answer: 0,
      explanation: "นี้เป็นผลต่างกำลังสอง: (x+2)² = 0, รากเดียว x = -2",
    },
    {
      id: "m3-quad-3",
      question: "ใช้สูตร quadratic หาค่า x: x^2 - 3x - 4 = 0",
      choices: ["x = 4, -1", "x = -4, 1", "x = 2, -2", "x = 3, -1"],
      answer: 0,
      explanation: "x = (3 ± √(9+16))/2 = (3 ± 5)/2, ได้ x = 4 หรือ x = -1",
    },
    {
      id: "m3-quad-4",
      question: "กราฟ y = x^2 - 4 ตัดแกน x ที่?",
      choices: ["x = ±2", "x = ±4", "x = 0", "x = 2"],
      answer: 0,
      explanation: "เมื่อ y = 0: x^2 = 4, ดังนั้น x = ±2",
    },
    {
      id: "m3-quad-5",
      question: "สมการ x^2 + 2x + 5 = 0 มีรากเป็นจำนวนจริงหรือไม่?",
      choices: ["ใช่", "ไม่ใช่", "รากเดียว", "ไม่สามารถบอกได้"],
      answer: 1,
      explanation: "Δ = 4 - 20 = -16 < 0, ไม่มีรากจำนวนจริง",
    },
  ],
  "m3-functions": [
    {
      id: "m3-func-1",
      question: "f(x) = 2x + 1, f(3) = ?",
      choices: ["5", "6", "7", "8"],
      answer: 2,
      explanation: "แทน x = 3: f(3) = 2(3) + 1 = 7",
    },
    {
      id: "m3-func-2",
      question: "ฟังก์ชัน f(x) = x^2, f(-2) = ?",
      choices: ["-4", "4", "2", "-2"],
      answer: 1,
      explanation: "f(-2) = (-2)² = 4",
    },
    {
      id: "m3-func-3",
      question: "โดเมนของ f(x) = √x คือ?",
      choices: ["x ≥ 0", "x > 0", "x ≤ 0", "ทุกจำนวนจริง"],
      answer: 0,
      explanation: "รากที่สองต้องมีจำนวนจริงไม่ติดลบ",
    },
    {
      id: "m3-func-4",
      question: "f(x) = 1/x, f(0) = ?",
      choices: ["0", "1", "ไม่มีกำหนด", "∞"],
      answer: 2,
      explanation: "หารด้วย 0 ไม่ได้ ดังนั้นไม่มีกำหนด",
    },
    {
      id: "m3-func-5",
      question: "ฟังก์ชัน f(x) = 3x - 2 เป็นฟังก์ชันเส้นตรงหรือไม่?",
      choices: ["ใช่", "ไม่ใช่", "เป็นฟังก์ชันกำลังสอง", "เป็นฟังก์ชันชี้กำลัง"],
      answer: 0,
      explanation: "อยู่ในรูป y = mx + b ดังนั้นเป็นเส้นตรง",
    },
  ],
  "m3-trigonometry": [
    {
      id: "m3-trig-1",
      question: "sin(30°) = ?",
      choices: ["1/2", "√3/2", "√2/2", "1"],
      answer: 0,
      explanation: "sin(30°) = 1/2",
    },
    {
      id: "m3-trig-2",
      question: "cos(60°) = ?",
      choices: ["1/2", "√3/2", "√2/2", "0"],
      answer: 0,
      explanation: "cos(60°) = 1/2",
    },
    {
      id: "m3-trig-3",
      question: "tan(45°) = ?",
      choices: ["0", "1", "√3", "ไม่มีกำหนด"],
      answer: 1,
      explanation: "tan(45°) = 1",
    },
    {
      id: "m3-trig-4",
      question: "sin²θ + cos²θ = ?",
      choices: ["0", "1", "tan θ", "sin 2θ"],
      answer: 1,
      explanation: "เอกลักษณ์พีทาโกรัส: sin²θ + cos²θ = 1",
    },
    {
      id: "m3-trig-5",
      question: "ในสามเหลี่ยมมุมฉาก ถ้า sin A = 3/5 cos A = ?",
      choices: ["3/5", "4/5", "5/3", "5/4"],
      answer: 1,
      explanation: "ใช้ sin²A + cos²A = 1: cos A = √(1 - 9/25) = 4/5",
    },
  ],
  "m3-triangle-trig": [
    {
      id: "m3-tri-1",
      question: "สามเหลี่ยมมุมฉากด้านตรงข้าม 5 ด้านติดกัน 12 หา sin θ?",
      choices: ["5/13", "12/13", "5/12", "12/5"],
      answer: 0,
      explanation: "ตรงข้าม = 5, ตรงข้ามมุมฉาก = √(5²+12²) = 13, sin = 5/13",
    },
    {
      id: "m3-tri-2",
      question: "สามเหลี่ยมมุมฉาก a=8, b=15 หา c?",
      choices: ["17", "23", "15", "8"],
      answer: 0,
      explanation: "c = √(8² + 15²) = √(64 + 225) = √289 = 17",
    },
    {
      id: "m3-tri-3",
      question: "sin θ = 4/5 ในสามเหลี่ยมมุมฉาก cos θ = ?",
      choices: ["3/5", "4/5", "5/3", "5/4"],
      answer: 0,
      explanation: "ตรงข้าม = 4, ตรงข้ามมุมฉาก = 5, ติดกัน = 3, cos = 3/5",
    },
    {
      id: "m3-tri-4",
      question: "มุมที่สูง 30 องศา ด้านตรงข้าม 10 หา ตรงข้ามมุมฉาก?",
      choices: ["20", "10√3", "10", "20√3"],
      answer: 0,
      explanation: "ตรงข้ามมุมฉาก = 2 × ตรงข้าม = 2 × 10 = 20",
    },
    {
      id: "m3-tri-5",
      question: "tan θ = 3/4 หา sin θ?",
      choices: ["3/5", "4/5", "3/4", "4/3"],
      answer: 0,
      explanation: "ตรงข้าม = 3, ติดกัน = 4, ตรงข้ามมุมฉาก = 5, sin = 3/5",
    },
  ],
  "m3-geometry-apps": [
    {
      id: "m3-geo-1",
      question: "ปริมาตรลูกคลี่有四เหลี่ยมฐาน 6 สูง 10 คือ?",
      choices: ["60", "120", "180", "240"],
      answer: 1,
      explanation: "พื้นที่ฐาน = 6² = 36, ปริมาตร = 1/3 × 36 × 10 = 120",
    },
    {
      id: "m3-geo-2",
      question: "พื้นที่ผิวทรงกลมรัศมี 7 คือ?",
      choices: ["49π", "98π", "147π", "196π"],
      answer: 3,
      explanation: "พื้นที่ผิว = 4πr² = 4π × 49 = 196π",
    },
    {
      id: "m3-geo-3",
      question: "ปริมาตรทรงกระบอกรัศมี 3 สูง 5 คือ?",
      choices: ["15π", "45π", "90π", "135π"],
      answer: 3,
      explanation: "ปริมาตร = πr²h = π × 9 × 5 = 45π",
    },
    {
      id: "m3-geo-4",
      question: "มุมระหว่างเส้นตรงและระนาบคือ?",
      choices: ["0°", "90°", "180°", "45°"],
      answer: 0,
      explanation: "เส้นตรงอยู่ในระนาบ ดังนั้นมุม = 0°",
    },
    {
      id: "m3-geo-5",
      question: "ระยะทางระหว่างจุด (0,0) กับ (3,4) คือ?",
      choices: ["5", "7", "25", "√7"],
      answer: 0,
      explanation: "ใช้สูตรระยะทาง: √((3-0)² + (4-0)²) = √(9+16) = 5",
    },
  ],
}