import type { TopicQuestions } from "./types"

export const M4_QUESTIONS: TopicQuestions = {
  "m4-advanced-algebra": [
    {
      id: "m4-alg-1",
      question: "√(x + 3) = 5, ค่า x คือ?",
      choices: ["22", "25", "28", "2"],
      answer: 2,
      explanation: "ยกกำลังสองทั้งสองด้าน: x + 3 = 25, x = 22",
    },
    {
      id: "m4-alg-2",
      question: "x^2 = 16, ค่า x คือ?",
      choices: ["4", "-4", "±4", "8"],
      answer: 2,
      explanation: "x = ±√16 = ±4",
    },
    {
      id: "m4-alg-3",
      question: "|2x - 5| = 9, ค่า x คือ?",
      choices: ["x = 7 หรือ -2", "x = 7 หรือ 2", "x = -7 หรือ 2", "x = 14"],
      answer: 0,
      explanation: "2x - 5 = 9 → x = 7, หรือ 2x - 5 = -9 → x = -2",
    },
    {
      id: "m4-alg-4",
      question: "1/(x + 2) = 3, ค่า x คือ?",
      choices: ["x = -5/3", "x = -1/3", "x = 1/3", "x = 5/3"],
      answer: 1,
      explanation: "x + 2 = 1/3, x = 1/3 - 2 = -5/3",
    },
    {
      id: "m4-alg-5",
      question: "x^(1/2) = 4, ค่า x คือ?",
      choices: ["2", "8", "16", "64"],
      answer: 2,
      explanation: "ยกกำลังสอง: x = 4² = 16",
    },
  ],
  "m4-sequences": [
    {
      id: "m4-seq-1",
      question: "ลำดับเลขคณิต a1 = 3, d = 4, a5 = ?",
      choices: ["15", "19", "23", "7"],
      answer: 1,
      explanation: "a5 = a1 + 4d = 3 + 16 = 19",
    },
    {
      id: "m4-seq-2",
      question: "ลำดับเลขเรียง成分 a1 = 2, r = 3, a4 = ?",
      choices: ["18", "24", "54", "81"],
      answer: 2,
      explanation: "a4 = a1 × r³ = 2 × 27 = 54",
    },
    {
      id: "m4-seq-3",
      question: "ผลรวม 5 พจน์แรกของลำดับเลขคณิต a1 = 1, d = 2 คือ?",
      choices: ["15", "20", "25", "30"],
      answer: 2,
      explanation: "S5 = 5/2 × (2(1) + 4(2)) = 5/2 × 10 = 25",
    },
    {
      id: "m4-seq-4",
      question: "ลำดับ 2, 6, 18, 54, ... เป็นลำดับอะไร?",
      choices: ["เลขคณิต", "เลขเรียง成分", "ฟิโบนัคชี", "เรียงตัวเลข"],
      answer: 1,
      explanation: "หารแต่ละพจน์กับพจน์ก่อนหน้าได้ 3 เสมอ",
    },
    {
      id: "m4-seq-5",
      question: "a1 = 4, a3 = 16 ในลำดับเลขเรียง成分 r คือ?",
      choices: ["2", "4", "8", "√4"],
      answer: 0,
      explanation: "a3 = a1 × r²: 16 = 4r², r² = 4, r = 2",
    },
  ],
  "m4-coordinate-geometry": [
    {
      id: "m4-cord-1",
      question: "ระยะทางระหว่าง (0,0) กับ (3,4) คือ?",
      choices: ["5", "7", "25", "√7"],
      answer: 0,
      explanation: "√((3-0)² + (4-0)²) = √(9+16) = 5",
    },
    {
      id: "m4-cord-2",
      question: "จุดกึ่งกลางของ (2,4) กับ (6,8) คือ?",
      choices: ["(4,6)", "(3,5)", "(5,7)", "(8,12)"],
      answer: 0,
      explanation: "((2+6)/2, (4+8)/2) = (4, 6)",
    },
    {
      id: "m4-cord-3",
      question: "ความชันของเส้นผ่าน (1,2) กับ (3,6) คือ?",
      choices: ["2", "3", "4", "1"],
      answer: 0,
      explanation: "m = (6-2)/(3-1) = 4/2 = 2",
    },
    {
      id: "m4-cord-4",
      question: "สมการเส้นตรงที่ผ่าน (0,3) และมีความชัน 2 คือ?",
      choices: ["y = 2x + 3", "y = 2x - 3", "y = 3x + 2", "y = -2x + 3"],
      answer: 0,
      explanation: "y = mx + b, m = 2, b = 3",
    },
    {
      id: "m4-cord-5",
      question: "ระยะทางระหว่าง (1,1) กับ (4,5) คือ?",
      choices: ["5", "√13", "√25", "4"],
      answer: 0,
      explanation: "√((4-1)² + (5-1)²) = √(9+16) = 5",
    },
  ],
  "m4-circles": [
    {
      id: "m4-circ-1",
      question: "วงกลม x² + y² = 25 มีรัศมีเท่าไร?",
      choices: ["5", "10", "25", "√5"],
      answer: 0,
      explanation: "r² = 25, ดังนั้น r = 5",
    },
    {
      id: "m4-circ-2",
      question: "จุด (3,4) อยู่บนวงกลม x² + y² = 25 หรือไม่?",
      choices: ["ใช่", "ไม่ใช่", "อยู่ภายใน", "อยู่ภายนอก"],
      answer: 0,
      explanation: "3² + 4² = 9 + 16 = 25",
    },
    {
      id: "m4-circ-3",
      question: "ศูนย์กลาง (0,0) รัศมี 5 สมมาตรวงกลมคือ?",
      choices: ["x² + y² = 25", "x² + y² = 5", "(x-5)² + y² = 25", "x² + y² = 10"],
      answer: 0,
      explanation: "สมมาตรวงกลม: (x-h)² + (y-k)² = r²",
    },
    {
      id: "m4-circ-4",
      question: "มุม inscribed ในวงกลมคือ?",
      choices: ["90°", "60°", "45°", "180°"],
      answer: 0,
      explanation: "มุม inscribed กับเส้นผ่านศูนย์กลางเป็นมุมฉาก",
    },
    {
      id: "m4-circ-5",
      question: "เส้นผ่านศูนย์กลางยาว 10 รัศมีคือ?",
      choices: ["5", "10", "20", "π"],
      answer: 0,
      explanation: "เส้นผ่านศูนย์กลาง = 2r, ดังนั้น r = 5",
    },
  ],
  "m4-statistics-advanced": [
    {
      id: "m4-stat-1",
      question: "ส่วนเบี่ยงเบนมาตรฐานวัดอะไร?",
      choices: ["การกระจายข้อมูล", "ค่าเฉลี่ย", "ค่ากลาง", "ความถี่"],
      answer: 0,
      explanation: "ส่วนเบี่ยงเบนมาตรฐานวัดการกระจายของข้อมูล",
    },
    {
      id: "m4-stat-2",
      question: "กราฟ box plot แสดงอะไร?",
      choices: ["การกระจายข้อมูล", "ความสัมพันธ์", "สัดส่วน", "แนวโน้ม"],
      answer: 0,
      explanation: "Box plot แสดงค่ากลาง ค่าต่ำสุด สูงสุด และควอไทล์",
    },
    {
      id: "m4-stat-3",
      question: "ควอไทล์ที่ 1 (Q1) คือ?",
      choices: ["ค่าที่ 25%", "ค่าที่ 50%", "ค่าที่ 75%", "ค่าเฉลี่ย"],
      answer: 0,
      explanation: "Q1 คือค่าที่แบ่งข้อมูล 25% ล่าง",
    },
    {
      id: "m4-stat-4",
      question: "ความสัมพันธ์ระหว่างสองตัวแปรแสดงด้วย?",
      choices: ["กราฟ scatter", "กราฟแท่ง", "แผนภูมิวงกลม", "กราฟเส้น"],
      answer: 0,
      explanation: "Scatter plot แสดงความสัมพันธ์ระหว่างตัวแปรสองตัว",
    },
    {
      id: "m4-stat-5",
      question: "ค่าที่ผิดปกติ (outlier) คือ?",
      choices: ["ค่าที่ห่างจากกลุ่มมาก", "ค่าเฉลี่ย", "ค่ามัธยฐาน", "ฐานนิยม"],
      answer: 0,
      explanation: "ค่าที่ผิดปกติคือค่าที่อยู่ห่างจากกลุ่มข้อมูลหลัก",
    },
  ],
}