import type { TopicQuestions } from "./types"

export const M5_QUESTIONS: TopicQuestions = {
  "m5-trigonometry-advanced": [
    {
      id: "m5-trig-1",
      question: "sin(120°) = ?",
      choices: ["√3/2", "1/2", "-√3/2", "-1/2"],
      answer: 0,
      explanation: "sin(120°) = sin(180°-60°) = sin(60°) = √3/2",
    },
    {
      id: "m5-trig-2",
      question: "cos(150°) = ?",
      choices: ["√3/2", "-√3/2", "1/2", "-1/2"],
      answer: 1,
      explanation: "cos(150°) = cos(180°-30°) = -cos(30°) = -√3/2",
    },
    {
      id: "m5-trig-3",
      question: "tan(210°) = ?",
      choices: ["√3/3", "-√3/3", "√3", "-√3"],
      answer: 1,
      explanation: "tan(210°) = tan(180°+30°) = tan(30°) = √3/3 แต่อยู่ในช่วงที่ 3 ดังนั้นติดลบ",
    },
    {
      id: "m5-trig-4",
      question: "sin(2θ) = ?",
      choices: ["2sinθcosθ", "sin²θ + cos²θ", "cos²θ - sin²θ", "tanθ"],
      answer: 0,
      explanation: "สูตรมุมสองเท่า: sin(2θ) = 2sinθcosθ",
    },
    {
      id: "m5-trig-5",
      question: "cos(2θ) ในรูปของ sinθ คือ?",
      choices: ["1 - 2sin²θ", "2sin²θ - 1", "1 - cos²θ", "2cos²θ - 1"],
      answer: 0,
      explanation: "cos(2θ) = 1 - 2sin²θ",
    },
  ],
  "m5-calculus-basics": [
    {
      id: "m5-calc-1",
      question: "ลิมิต lim x→2 ของ (x + 3) คือ?",
      choices: ["2", "3", "5", "ไม่มีกำหนด"],
      answer: 2,
      explanation: "ฟังก์ชันต่อเนื่อง แทน x = 2 ได้ 5",
    },
    {
      id: "m5-calc-2",
      question: "ลิมิต lim x→0 ของ (sin x)/x คือ?",
      choices: ["0", "1", "∞", "ไม่มีกำหนด"],
      answer: 1,
      explanation: "ลิมิตพิเศษ: lim x→0 sin(x)/x = 1",
    },
    {
      id: "m5-calc-3",
      question: "f(x) = x^2, f'(x) = ?",
      choices: ["x", "2x", "x^3", "2"],
      answer: 1,
      explanation: "กฎกำลัง: d/dx(x^n) = nx^(n-1), ดังนั้น 2x",
    },
    {
      id: "m5-calc-4",
      question: "อัตราการเปลี่ยนแปลงทันทีของ f(x) = 3x + 2 คือ?",
      choices: ["3", "2", "3x", "x"],
      answer: 0,
      explanation: "อัตราการเปลี่ยนแปลงทันทีคืออนุพันธ์ = 3",
    },
    {
      id: "m5-calc-5",
      question: "ความชันของ f(x) = x^2 ที่ x = 1 คือ?",
      choices: ["1", "2", "3", "0"],
      answer: 1,
      explanation: "f'(x) = 2x, f'(1) = 2",
    },
  ],
  "m5-derivatives": [
    {
      id: "m5-der-1",
      question: "อนุพันธ์ของ 5x + 3 คือ?",
      choices: ["5", "8", "5x", "3"],
      answer: 0,
      explanation: "อนุพันธ์ของ 5x คือ 5, อนุพันธ์ของ 3 คือ 0",
    },
    {
      id: "m5-der-2",
      question: "อนุพันธ์ของ x^3 คือ?",
      choices: ["3x^2", "3x", "x^2", "3"],
      answer: 0,
      explanation: "d/dx(x^3) = 3x^2",
    },
    {
      id: "m5-der-3",
      question: "อนุพันธ์ของ sin(x) คือ?",
      choices: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"],
      answer: 0,
      explanation: "กฎอนุพันธ์มาตรฐาน: d/dx sin(x) = cos(x)",
    },
    {
      id: "m5-der-4",
      question: "อนุพันธ์ของ e^x คือ?",
      choices: ["xe^(x-1)", "e^x", "ln(x)", "1/x"],
      answer: 1,
      explanation: "e^x เป็นอนุพันธ์ของตัวเอง",
    },
    {
      id: "m5-der-5",
      question: "อนุพันธ์ของ ln(x) คือ?",
      choices: ["1/x", "x", "ln(x)", "e^x"],
      answer: 0,
      explanation: "d/dx ln(x) = 1/x",
    },
  ],
  "m5-probability-advanced": [
    {
      id: "m5-prob-1",
      question: "การแจกแจงปกติมีลักษณะอย่างไร?",
      choices: ["เป็น钟形", "เป็นรูปสี่เหลี่ยม", "เป็นรูปสามเหลี่ยม", "เป็นรูปวงกลม"],
      answer: 0,
      explanation: "การแจกแจงปกติมีกราฟเป็น钟形 (bell curve)",
    },
    {
      id: "m5-prob-2",
      question: "ค่าเฉลี่ยของการแจกแจงปกติคือ?",
      choices: ["มัธยฐาน", "ฐานนิยม", "ส่วนเบี่ยงเบน", "ความน่าจะเป็น"],
      answer: 0,
      explanation: "ในการแจกแจงปกติ ค่าเฉลี่ย = มัธยฐาน = ฐานนิยม",
    },
    {
      id: "m5-prob-3",
      question: "ส่วนเบี่ยงเบนมาตรฐานวัด?",
      choices: ["การกระจาย", "ตำแหน่ง", "ความถี่", "ความน่าจะเป็น"],
      answer: 0,
      explanation: "ส่วนเบี่ยงเบนมาตรฐานวัดการกระจายของข้อมูล",
    },
    {
      id: "m5-prob-4",
      question: "การแจกแจงแบบทวินาม (binomial) ใช้เมื่อ?",
      choices: ["ลองหลายครั้งได้ 2 ผลลัพธ์", "ข้อมูลต่อเนื่อง", "เวลาต่อเนื่อง", "อุณหภูมิ"],
      answer: 0,
      explanation: "Binomial distribution ใช้กับ Bernoulli trial",
    },
    {
      id: "m5-prob-5",
      question: "ความน่าจะเป็นของ A หรือ B ถ้าไม่เกี่ยวข้องคือ?",
      choices: ["P(A) + P(B)", "P(A) × P(B)", "P(A|B)", "P(A∩B)"],
      answer: 0,
      explanation: "เหตุการณ์ไม่เกี่ยวข้อง: P(A∪B) = P(A) + P(B)",
    },
  ],
}