import type { TopicQuestions } from "./types"

export const M6_QUESTIONS: TopicQuestions = {
  "m6-limits": [
    {
      id: "m6-lim-1",
      question: "lim x→2 ของ (x + 3) คือ?",
      choices: ["2", "3", "5", "ไม่มีกำหนด"],
      answer: 2,
      explanation: "ฟังก์ชันต่อเนื่อง แทน x = 2 ได้ 5",
    },
    {
      id: "m6-lim-2",
      question: "lim x→0 ของ (sin x)/x คือ?",
      choices: ["0", "1", "∞", "ไม่มีกำหนด"],
      answer: 1,
      explanation: "ลิมิตพิเศษ: lim x→0 sin(x)/x = 1",
    },
    {
      id: "m6-lim-3",
      question: "lim x→∞ ของ 1/x คือ?",
      choices: ["0", "1", "∞", "-∞"],
      answer: 0,
      explanation: "เมื่อ x ใหญ่ขึ้น 1/x ใกล้ 0",
    },
    {
      id: "m6-lim-4",
      question: "lim x→3 ของ (x^2 - 9)/(x - 3) คือ?",
      choices: ["0", "3", "6", "ไม่มีกำหนด"],
      answer: 2,
      explanation: "แยกตัวประกอบ: (x-3)(x+3)/(x-3) = x+3, แทน x = 3 ได้ 6",
    },
    {
      id: "m6-lim-5",
      question: "lim x→0+ ของ 1/x คือ?",
      choices: ["0", "1", "∞", "-∞"],
      answer: 2,
      explanation: "เมื่อ x ใกล้ 0 จากด้านบวก 1/x ใกล้ ∞",
    },
  ],
  "m6-derivatives-advanced": [
    {
      id: "m6-der-1",
      question: "อนุพันธ์ของ x^3 คือ?",
      choices: ["3x^2", "3x", "x^2", "3"],
      answer: 0,
      explanation: "d/dx(x^3) = 3x^2",
    },
    {
      id: "m6-der-2",
      question: "อนุพันธ์ของ sin(x) คือ?",
      choices: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"],
      answer: 0,
      explanation: "กฎอนุพันธ์มาตรฐาน: d/dx sin(x) = cos(x)",
    },
    {
      id: "m6-der-3",
      question: "อนุพันธ์ของ e^x คือ?",
      choices: ["xe^(x-1)", "e^x", "ln(x)", "1/x"],
      answer: 1,
      explanation: "e^x เป็นอนุพันธ์ของตัวเอง",
    },
    {
      id: "m6-der-4",
      question: "อนุพันธ์ของ ln(x) คือ?",
      choices: ["1/x", "x", "ln(x)", "e^x"],
      answer: 0,
      explanation: "d/dx ln(x) = 1/x",
    },
    {
      id: "m6-der-5",
      question: "อนุพันธ์ของ cos(2x) คือ?",
      choices: ["-2sin(2x)", "2sin(2x)", "-sin(2x)", "sin(2x)"],
      answer: 0,
      explanation: "ใช้โซ่รุ่น: d/dx cos(u) = -sin(u) × du/dx = -sin(2x) × 2",
    },
  ],
  "m6-integrals": [
    {
      id: "m6-int-1",
      question: "ปริพันธ์ของ 2x dx คือ?",
      choices: ["x^2 + C", "2x^2 + C", "x + C", "2 + C"],
      answer: 0,
      explanation: "ย้อนกลับกฎกำลัง: ∫2x dx = x^2 + C",
    },
    {
      id: "m6-int-2",
      question: "ปริพันธ์ของ 1 dx คือ?",
      choices: ["0 + C", "x + C", "1/x + C", "x^2 + C"],
      answer: 1,
      explanation: "∫1 dx = x + C",
    },
    {
      id: "m6-int-3",
      question: "ปริพันธ์ของ x^2 dx คือ?",
      choices: ["x^3/3 + C", "2x + C", "x^3 + C", "x/2 + C"],
      answer: 0,
      explanation: "∫x^2 dx = x^3/3 + C",
    },
    {
      id: "m6-int-4",
      question: "∫_0^2 x dx = ?",
      choices: ["2", "4", "1", "0"],
      answer: 0,
      explanation: "∫x dx = x^2/2, แทน 2 และ 0: 2^2/2 - 0 = 2",
    },
    {
      id: "m6-int-5",
      question: "ปริพันธ์ของ sin(x) dx คือ?",
      choices: ["cos(x) + C", "-cos(x) + C", "sin(x) + C", "-sin(x) + C"],
      answer: 1,
      explanation: "∫sin(x) dx = -cos(x) + C",
    },
  ],
  "m6-applications": [
    {
      id: "m6-app-1",
      question: "พื้นที่ใต้ f(x) = x จาก 0 ถึง 2 คือ?",
      choices: ["2", "4", "1", "0"],
      answer: 0,
      explanation: "∫_0^2 x dx = [x^2/2]_0^2 = 2",
    },
    {
      id: "m6-app-2",
      question: "ความยาวของเส้นโค้ง y = x^2 จาก 0 ถึง 1 คือ?",
      choices: ["≈ 1.47", "≈ 2.23", "≈ 0.5", "≈ 1"],
      answer: 0,
      explanation: "ใช้สูตรความยาวเส้นโค้ง: ∫√(1 + (dy/dx)²) dx",
    },
    {
      id: "m6-app-3",
      question: "ปริมาตรของ solid of revolution รัศมี r สูง h คือ?",
      choices: ["πr²h", "2πrh", "4/3πr³", "πr²"],
      answer: 0,
      explanation: "ปริมาตรทรงกระบอก = πr²h",
    },
    {
      id: "m6-app-4",
      question: "งาน done by force F(x) = 2x จาก 0 ถึง 3 คือ?",
      choices: ["9", "6", "3", "0"],
      answer: 0,
      explanation: "∫_0^3 2x dx = [x^2]_0^3 = 9",
    },
    {
      id: "m6-app-5",
      question: "ศูนย์กลางของมวลของ thin rod ตั้งแต่ 0 ถึง L คือ?",
      choices: ["L/2", "L/3", "L/4", "L"],
      answer: 0,
      explanation: "ศูนย์กลางอยู่กึ่งกลาง: L/2",
    },
  ],
  "m6-advanced-probability": [
    {
      id: "m6-prob-1",
      question: "การแจกแจง binomial n=10, p=0.5 ค่าเฉลี่ยคือ?",
      choices: ["5", "10", "0.5", "2.5"],
      answer: 0,
      explanation: "ค่าเฉลี่ย binomial = np = 10 × 0.5 = 5",
    },
    {
      id: "m6-prob-2",
      question: "การแจกแจงปกติ Z-score 0 หมายถึง?",
      choices: ["ค่าเฉลี่ย", "มัธยฐาน", "ฐานนิยม", "ส่วนเบี่ยงเบน"],
      answer: 0,
      explanation: "Z = 0 อยู่ที่ค่าเฉลี่ยของการแจกแจงปกติ",
    },
    {
      id: "m6-prob-3",
      question: "ความน่าจะเป็นของ Z > 1.96 ในการแจกแจงปกติคือ?",
      choices: ["0.025", "0.05", "0.95", "0.975"],
      answer: 0,
      explanation: "P(Z > 1.96) ≈ 0.025 (α = 0.05 two-tailed)",
    },
    {
      id: "m6-prob-4",
      question: "การแจกแจง Poisson ใช้เมื่อ?",
      choices: ["นับจำนวนเหตุการณ์ในช่วงเวลา", "ข้อมูลต่อเนื่อง", "สองผลลัพธ์", "การทดลองซ้ำ"],
      answer: 0,
      explanation: "Poisson distribution ใช้กับจำนวนเหตุการณ์ในช่วงเวลา/พื้นที่",
    },
    {
      id: "m6-prob-5",
      question: "ทวิภาค (binomial) กับ Bernoulli ต่างกันอย่างไร?",
      choices: ["Binomial = หลาย Bernoulli", "เหมือนกัน", "Bernoulli ใช้กับต่อเนื่อง", "ไม่มีความสัมพันธ์"],
      answer: 0,
      explanation: "Binomial distribution เป็นผลรวมของ Bernoulli trials",
    },
  ],
}